- harper-ls/Cargo.toml
To allow [Crates.io](https://crates.io/) , [lib.rs](https://lib.rs/) and the [Rust Digger](https://rust-digger.code-maven.com/) to link to it. See also [the manifest](https://doc.rust-lang.org/cargo/reference/manifest.html#the-repository-field).
> It is better to use the repository field

- harper-comments/src/comment_parsers/unit.rs
One day ago, [a commit](https://github.com/elijah-potter/harper/commit/bd21b53530469d2b18283ab0aeabdedf8a3342ed) addressing issue #132 introduced a debug statement that pollutes CLI output when running `just dogfood`
> fix: remove dbg

- justfile
Shortly after installation, I ran `just dogfood` in order to gauge the speed of Harper on my machine . It seemed slow, each file taking almost a second to lint. 
The call to `cargo run --release` adds a decent amount of overhead to each file in the loop, so instead we can use `cargo build --release` once before the loop to ensure the binary is built, and then run the binary directly within the loop. After this change, each file lints in ~200ms instead of ~1s
> fix: speed up `just dogfood` execution

- harper-ls/README.md
- harper-ls/src/config.rs
Adds `fileDictPath` configuration, akin to `userDictPath`.
The implementation and documentation mirror the existing implementation of `userDictPath`, and hence only make the smallest set of changes required to provide a configurable file dictionary path.
> feat: allow to configure file dictionary path

- harper-core/src/spell/hunspell/mod.rs
The test [`spell::hunspell::tests::correctly_expands_test_files`](https://github.com/Cryolitia/harper/blob/4e6564a9b9c120396972d984ba2a950dc6db18f9/harper-core/src/spell/hunspell/mod.rs#L88-L100) iterates over a HashMap and collects the results, but the results assume that the collected array is in a specific order. Rust does not guarantee the order in which HashMap is iterated, and the order depends on the specific implementation of Rust's hash function on the platform.
It is on the [Rust Doc](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.iter) that said:
> An iterator visiting all key-value pairs in **arbitrary order**. The iterator element type is `(&'a K, &'a V)`.
> Due to differences in endianness and type sizes, data fed by Hash to a Hasher should not be …
> fix: test 'spell::hunspell::tests::correctly_expands_test_files' failed

- harper-core/src/linting/an_a.rs
The sentence "This is not an ML-based system." is grammatical, because the an/a vowel rule applies to "ML" (an initialism).
Another approach would be to add a new document iterator (similar to `iter_words`) that splits on hyphens too, and use that iterator.
> fix: break words on hyphens for the `an_a` lint

- harper-ls/src/main.rs
[Tokio has two different types of threads](https://github.com/tokio-rs/tokio/discussions/3858#discussioncomment-869878):
- Worker threads: for async things
- Blocking threads: main and spawn_blocking
I limited the number of worker threads to 4, but the actual number of threads should hover around 5.
I'm not certain whether we spawn any blocking threads other than main, but if we do it should be minimal.
> fix(#198): limit tokio threads to 4 (+ main)

- .github/workflows/build_harper_ls.yml
- .github/workflows/build_web.yml
- .github/workflows/package_vscode_plugin.yml
- .github/workflows/precommit.yml
- packages/vscode-plugin/CHANGELOG.md
- Change "Unreleased" section in `CHANGELOG.md` to "0.12.0". It seems this was left out in the last release.
- Format workflows with Prettier.
- Update actions to their latest versions. This should fix the warnings we get on runs about old Node.js versions.
- Run Package VS Code Plugin workflow on PRs.
> Minor updates

- harper-comments/src/comment_parser.rs
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentItem has a list of language ids, and it recommends "python", not "py".
> Use standard "python" language id, add support for missing `.py` extension

- harper-ls/src/backend.rs
- packages/vscode-plugin/src/extension.ts
- packages/vscode-plugin/src/tests/suite/integration.test.ts
I noticed that config updates don't get reflected in the editor unless `harper-ls` is restarted, at least for VSCode. Hence, my original solution to just restart it, but that feels like such a brute force way and it clears all the diagnostics within the workspace. So, I thought it'd be better if the new config is reflected and the diagnostics are updated when `did_change_configuration` is called.
P.S. This is my first time writing any Rust so I may have made a mistake somewhere.
> Improve config change handling

- .github/workflows/build_harper_ls.yml
- .github/workflows/package_vscode_plugin.yml
These workflows fail on draft PRs anyway, and I believe they will get run when the draft status is removed.
I still think it's important to have the precommit workflow run, but these others don't seem too important for a draft.
> ci: disable packaging and building workflows on draft PRs

- harper-core/src/linting/spelled_numbers.rs
- Fix comments
- Change from suggesting if <= 10 to < 10
- Expand spelling function (110 would give stack overflow before)
- Update tests accordingly
I wasn't able to find an "Automattic style guide" as referenced in recent
commits on this, but it is rather standard to spell out numbers under but not
including 10. This is what APA does, and I believe MLA as well.
Recent commits also didn't update doc comments to reflect new behavior, so I
fixed that.
One thing to keep in mind, but I don't think is implemented yet, is that
numbers beginning sentences should always be spelled out, so it would be best
to expand behavior to include this in further enhancements.
> fix(core): updates to SpelledNumbers

- harper-cli/src/main.rs
- justfile
Added a command to harper-cli and the justfile that visually displays spans on a parsed file.
It can be painstaking to verify that a parser is working correctly when writing one, but this command makes it easier to verify that the correct spans are being chosen.
I created this to assist me in implementing the typst parser (#302), but am spinning it off into it's own PR since it is pretty distinct.
The output is rather cluttered because it prints the span numbers as well. I'm split on this one, it can be helpful because you can cross-reference with the output of `just parse` to check what each span corresponds to, but it also makes the output less readable (or at least a lot longer vertically).
Example usage:
Note: it alternates colors to make adjacent spans stand out.
> feat: Span visualization command

- packages/vscode-plugin/CHANGELOG.md
- packages/vscode-plugin/README.md
- packages/vscode-plugin/package.json
- packages/vscode-plugin/src/extension.ts
Closes #321
I didn't add a test for the new setting since it'd be hard to distinguish if the extension is actually using a different binary or if it's just ignoring the setting and is using what's bundled because output wise, changing to a different executable should yield the same diagnostics in the editor.
> Support using a different `harper-ls` executable than the one bundled in the VSCode extension

- Cargo.lock
- harper-comments/Cargo.toml
- harper-comments/src/comment_parser.rs
- packages/vscode-plugin/CHANGELOG.md
- packages/vscode-plugin/package.json
- packages/vscode-plugin/src/tests/fixtures/languages/haskell.hs
- packages/vscode-plugin/src/tests/suite/languages.test.ts
Could supersede or be merged after #332.
> feat(vscode-plugin): Add Haskell Support

- README.md
- harper-ls/README.md
Can revert first commit if you want to point to the `harper-ls` subdirectory initially. I was just looking for the website.
> docs: Fixup README links for language server integration

- harper-core/src/language_detection.rs
- harper-core/src/lexing/email_address.rs
- harper-core/src/lexing/hostname.rs
- harper-core/src/parsers/markdown.rs
- justfile
> refactor: remove raw hashes that are unnecessary

- harper-cli/src/main.rs
- **feat(spans-visual): mark unlintable spans as red**
- **feat(spans-visual): spans visual defaults to hiding newline spans**
Taken from #302
> feat: Span View Command Improvements

- packages/vscode-plugin/package.json
- packages/vscode-plugin/src/tests/fixtures/languages/CMakeLists.txt
- packages/vscode-plugin/src/tests/suite/languages.test.ts
Add CMake support to the VSCode extension as per #353.
As an aside, I was about to update the changelog but I noticed that it was removed in ace693c00fe7128919c545ffbd22ec0b176b2fcc with the reasoning that it doesn't get updated. I just wanted to ask, what exactly wasn't being updated? Since, as far as I can recall, it was updated every time the extension was. Did it mean that the `## Unreleased` section wasn't being updated to the correct version every release? If so, that can be remedied by adding a command to also bump it in the `justfile` `bump-versions` recipe. I can add that to this PR, if you think it's a good idea.
> feat(vscode-plugin): Add CMake Support

- harper-wasm/src/lib.rs
- packages/harper.js/src/Linter.ts
- packages/harper.js/src/LocalLinter.ts
- packages/harper.js/src/WorkerLinter/index.ts
- packages/harper.js/src/main.ts
We want to expose a variety of markup languages to consumers of `harper.js`. This PR will expose `plaintext` and `markdown` as options.
> feat(harper.js): added ability to configure the markup language

- harper-ls/src/backend.rs
- packages/vscode-plugin/package.json
- packages/vscode-plugin/src/tests/fixtures/languages/literate-haskell.lhs
- packages/vscode-plugin/src/tests/fixtures/languages/typst.typ
- packages/vscode-plugin/src/tests/suite/languages.test.ts
- packages/web/src/app.css
- packages/web/src/routes/docs/integrations/language-server/+page.md
- Support Literate Haskell. I used `literate haskell` as the language ID instead of `lhaskell` since [that's what's used by the official VSCode Haskell extension](https://github.com/haskell/vscode-haskell/blob/cf7df9a68f8d2c4d42a4b061531652b644cc5b36/package.json#L63).
- Support Typst.
- Update the supported languages section of the docs.
- Alphabetize the languages.
- Add missing languages.
- Update language names based on [the spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentItem).
- Update the language IDs to reflect what's currently in the codebase.
- Remove the ❎s since they were hard to spot. I didn't even notice that there were ❎s and thought all of them were ✅s until I looked at the table closely. I don't think removing …
> feat(vscode-plugin): Add Literate Haskell and Typst Support + some doc updates

- harper-cli/src/main.rs
- harper-ls/src/main.rs
Clap has `about` and `version` attributes that can be added to provide users with a bit more info.
- Added `#[command(about, version)]` to harper-ls
- Added `#[command(about, version)]` to harper-cli
- Added short doc comment about harper-cli being a debugging tool
- Doc comment will be used for about and will appear in the help menu of harper-cli
Closes #393
> feat(#393): add clap version & about attributes

- harper-comments/src/comment_parsers/jsdoc.rs
- harper-core/src/linting/pronoun_contraction/avoid_contraction.rs
- harper-core/src/linting/spelled_numbers.rs
- harper-core/src/parsers/mask.rs
- harper-core/src/token_kind.rs
- harper-ls/src/config.rs
- packages/harper.js/src/loadWasm.ts
- packages/web/src/routes/+page.svelte
- packages/web/src/routes/docs/contributors/architecture/+page.md
- packages/web/src/routes/docs/contributors/committing/+page.md
- packages/web/src/routes/docs/contributors/environment/+page.md
- packages/web/src/routes/docs/integrations/neovim/+page.md
In `mask.rs` I was confused by 'between the last chunk".
Normally 'between' means between two things.
I wasn't sure if this should mean 'within the last chunk' or 'between the last two chunks' or 'between the last chunk and this chunk' etc, so I went with what I thought was the most likely. You better check.
Sorry I didn't run `just format` and `just precommit` because I don't know what those are and a quick Google didn't help. Git, GitHub, and build systems are still weak points.
> typos/spelling/grammar fixes in comments, docs, and strings

- .github/workflows/fuzz.yml
- .github/workflows/precommit.yml
- harper-core/src/lexing/email_address.rs
- harper-core/src/lexing/hostname.rs
- harper-core/src/parsers/markdown.rs
- harper-core/src/title_case.rs
- harper-core/src/token.rs
- justfile
We've had some issues (namely #373) that got through the cracks of our property-based testing. This PR aims to fix these issues and improve our testing process so they are less likely to be recreated in new modules.
> fix(core): harden title case module

- harper-core/dictionary.dict
- harper-core/src/patterns/is_not_title_case.rs
- harper-core/src/title_case.rs
- harper-core/tests/run_tests.rs
- harper-core/tests/test_sources/lukas_homework.md
@lukasmwerner sent me a file that revealed two problems:
- If Harper attempted to make a chunk of text title case (that had a previously lower-case word at the end of input) it would try to access memory out of bounds.
- If the 'UnitedOrganization` rule encountered a correct capitalization of `United States`, it would create a false positive.
This PR solves both problems.
@lukasmwerner, would you mind compiling this branch and confirming that it solves those issues?
> fix(core): indexing problems

- packages/web/src/routes/docs/contributors/environment/+page.md
I changed
you'll need to the following programs available in your `$PATH`
to
you'll need the following programs available in your `$PATH`
But perhaps another fix is preferred, such as:
you'll need to have the following programs available in your `$PATH`
> fix typo: remove extraneous 'to'

- harper-core/src/linting/oxford_comma.rs
Recently, the code was updated to suggest the "Oxford comma" with an "or-enumeration".
This commit updates the description to reflect this addition.
> chore: update description of Oxford rule

- Cargo.lock
- harper-cli/Cargo.toml
- harper-cli/src/main.rs
- harper-ls/src/config.rs
- justfile
- packages/vscode-plugin/package.json
> feat: Update VSCode Config

- harper-core/dictionary.dict
- harper-core/src/linting/currency_placement.rs
- harper-core/src/linting/mod.rs
- harper-core/src/linting/pronoun_contraction/avoid_contraction.rs
- harper-core/src/linting/pronoun_contraction/mod.rs
- harper-core/src/linting/pronoun_contraction/should_contract.rs
In we solved #225, but the rule we created had an issue that resulted in an infinite loop. One would "fix" a problem, but the fix would create another problem that the same rule would pick up.
This demonstrated a hole in our testing tools, which this PR aims to fill. By checking to make sure all invocations of `assert_suggestion` result create no new lints, we can cut down on this kind of error significantly. 
By doing this in fact, we also found a bug in #376.
> fix(core): infinite lint loops

- harper-ls/src/backend.rs
- harper-ls/src/main.rs
We've been seeing a lot of erroneous logs being made (see #443), cluttering buffers and making debugging more challenging. This PR aims to reduce this clutter by:
1. Reducing the number of logs `harper-ls` produces.
2. Reducing the noise within each log.
> Clean Up `harper-ls` logs

- harper-core/src/linting/oxford_comma.rs
> fix(core): the Oxford comma applies to `nor` as well

- harper-wasm/src/lib.rs
- packages/harper.js/src/Linter.test.ts
- packages/harper.js/src/Linter.ts
- packages/harper.js/src/LocalLinter.ts
- packages/harper.js/src/WorkerLinter/index.ts
- packages/web/src/lib/DefaultNeovimConfig.svelte
- packages/web/src/routes/docs/integrations/neovim/+page.md
In editors like Obsidian, we need to know what actual values the default config holds. This PR takes a stateful approach to the matter, allowing you to call a method on a `Linter` to set its configuration to the global default.
This PR also adds a button that will copy a Neovim-specific version of this default configuration to the clipboard for use in Lua configuration of `harper-ls`.
If SveltePress/sveltepress#310 is implemented, we will replace the button with the more reader-friendly alternative.
>  feat(harper.js): added ability to explicitly set config to the default

- packages/web/src/routes/docs/contributors/author-a-rule/+page.md
Unless this means "obtain a setup for your environment" this should be the verb "to set up".
> fix instance of #384 in docs

- harper-core/src/linting/use_genitive.rs
1. awkward "preposition bracketing"
2. missing "for" in "looks for"
Other valid fixes for 1. would be
- Define the environment where the genitive case __should__ be used.
- Define the environment the genitive case __should__ be used in.
> fix two grammatical errors

- harper-core/src/linting/that_which.rs
"Repeat twice" is redundant and perhaps ambiguous. If you repeat a thing, you've already done it twice. If you repeat it twice have you now done it three times?
I asked an LLM to copyedit this, confirm whether it's a real redundancy, and ask it for a rewording. I think it did a better job than I could've done on my own:
- **Removed "twice"**: The phrase "Repeating the word 'that' twice" was changed to "Repeating the word 'that'" to eliminate redundancy. The concept of repetition inherently implies that it can occur multiple times, so specifying "twice" is unnecessary.
- **Clarified the second sentence**: The phrase "That which" was kept, but the context was made clearer by stating it as "The phrase that which is easier to read."
> Reword description of "that which" to avoid ironic redundancy

- harper-core/dictionary.dict
- harper-core/src/linting/plural_conjugate.rs
- harper-core/src/token_kind.rs
I saw some issues with this rule while working on some documentation. This PR sets "you" to be potentially plural and adds some test cases.
> Improvements to `PluralConjugate`

- harper-core/src/document.rs
when best-effort is an adjective it should by connected using a hyphen
> Apply rule from issue #465 to core document.rs

- harper-core/src/linting/an_a.rs
I noticed that the `AnA` linter did not detect the problem in:
```
A interface for an object that can perform linting actions.
```
This PR allows the rule to detect capital articles, thus allowing it to detect the error.
> fix(core): `AnA` linter did not recognize capital articles

- harper-core/src/linting/repeated_words.rs
Noticed that the repeated words linter wasn't picking `and` as a special case. This adds a test case for it and ensures it passes.
> fix(core): `RepeatedWords` now detects repeated `and` tokens

- harper-core/src/char_string.rs
- harper-core/src/linting/lint.rs
- harper-core/src/linting/lint_group.rs
- harper-core/src/linting/mod.rs
- harper-core/src/linting/pattern_linter.rs
- harper-core/src/patterns/is_not_title_case.rs
- harper-core/src/patterns/mod.rs
- harper-core/src/patterns/sequence_pattern.rs
- harper-core/src/spell/dictionary.rs
- harper-core/src/token.rs
- packages/web/src/routes/docs/contributors/author-a-rule/+page.md
In #501, it became clear that some aspects of the [Rust documentation](https://docs.rs/harper-core/latest/harper_core/) are lacking. This hopefully clears up much of that confusion.
> `harper-core` Documentation Updates

- harper-html/src/lib.rs
- harper-html/tests/run_tests.rs
- harper-html/tests/test_sources/issue_541.html
Fixes #541 by condensing spaces to achieve similar behavior to proper HTML parsers.
> feat(html): condense spaces like most HTML parsers

- harper-core/dictionary.dict
- harper-core/src/linting/lets_confusion/mod.rs
For some reason, "you" was marked as a verb, which caused #548.
> fix(core): #548 `you` is not a verb

- justfile
- packages/.prettierignore
This PR swaps from explicitly calling `just` for every dependency to using `just`'s built-in dependency deduplication. 
To test how long a build takes, I used `just precommit`, which builds and tests every module in the monorepo. To be sure I was getting accurate results, I ran `git clean -xf .` at the root of the repository before each run.
On `master` (i.e. without the changes introduced in this PR), `just precommit` took 521 seconds. After making the changes, `just precommit` took only 358 seconds, or 1.41x faster. Hopefully this will reduce our GitHub Actions usage.
Closes #351.
> build: use `just`-native dependency resolution

- README.md
- packages/web/src/routes/docs/contributors/introduction/+page.md
- packages/web/vite.config.ts
The Harper project has grown to a size where synchronous communication methods are now necessary. After careful deliberation, I've decided that a Discord server is an appropriate place for that. 
I've created the server. This PR just adds the link to the necessary spots on the website and README.
> feat(web): add link to the Discord server

- harper-core/src/linting/matcher.rs
Somehow this character got into this file: [`U+2028` Line Separator Unicode Character](https://www.compart.com/en/unicode/U+2028)
> clean up strange character at end-of-line

- harper-core/src/linting/repeated_words.rs
I was writing an article for my blog when I noticed that Harper wouldn't detect repetitions of the word `on`. This PR fixes that.
> fix(core): add `on` to the list of special cases

- justfile
Addresses #595 to add only `/M` for capitalized words = proper nouns but continue adding `/SM` for lowercase words = common nouns.
This means all nouns will be eligible for possessive but only common nouns will be eligible for plural.
For proper nouns that do have plurals, edit the curated dictionary manually.
> feat: change `just addnoun` to have different affixes as per #595

- harper-core/affixes.json
- justfile
The name 'affixes' turns out to be a misnomer since about a quarter or a third of them don't add any prefix or suffix but change a property such as the part-of-speech, or singular vs plural.
Another approach would be to switch from `json` to either [`JSON5`](https://json5.org/) or [`Hjson`](https://hjson.github.io/) for the `affixes.json` file.
> feat: adds a brief helpful comment to each entry describing its function

- harper-ls/src/backend.rs
I have yet to convince myself exactly where the deadlock(s) is happening, but I suspect it is somewhere here in the `update_document` function. I am not sure if the Helix IDE is unique in this case, but it throws a lot of document change events at the LSP as you type, doesn't look like a ton of de-bouncing is happening. So very possible for some concurrent update doc requests. I initially thought there were issues with the order of when the config lock and doc lock are grabbed, but the config lock is a Rwlock, leaving me unable to think of an actual deadlock scenario.
Still, this patch shows a great improvement as far as avoiding deadlocks, although I can't be sure it completely fixes it. Not super satisfying.
Two lock updates in the patch, both attempt to lower the time locks are held …
> fix(ls): release config lock to avoid deadlocks

- harper-core/src/linting/lint_group.rs
- harper-core/src/linting/mod.rs
- harper-core/src/linting/possessive_your.rs
- packages/vscode-plugin/README.md
- packages/web/src/routes/docs/integrations/visual-studio-code/+page.md
The feedback in #602 made me aware we weren't covering this.
I've also included some small fixes (like making sure both `OxfordCommas` and `NoOxfordCommas` aren't both enabled by default).
> feat(core): create rule for the possessive version of "you"

- packages/harper.js/src/Linter.bench.ts
- packages/harper.js/src/LocalLinter.ts
I had some issues while working on an integration. These configuration methods sometimes would take quite a while, which would block a queue. This PR increases visibility into these methods.
> bench(harper.js): add benchmarks for configuration methods

- packages/obsidian-plugin/src/lint.ts
By default any **transactions** that **changes** the line → By default any **transaction** that **changes** the line
(Alternatively, "By default any **transactions** that **change** the line" would also be correct.)
> grammar agreement in obsidion plugin comment

- harper-core/src/linting/matcher.rs
I know the logic here is up for replacement but I think this categorization will still help in various ways:
1. It will help elucidate different classes and types of replacements.
2. It will help us see which categories will be amenable to various kinds of automation.
3. It will help curators adding more lints in the meantime.
4. It also shows that some lints combine multiple kinds of problems while others don't fit well into any neat category. There is some fuzziness.
(I first sorted them alphabetically then grouped them, so the groups themselves are more in a kind of alphabetical order than any semantic order.)
> feat: split triggers in `matcher.rs` into categories with explanations

- .github/ISSUE_TEMPLATE/report-grammatical-error.md
Apologies if this was intentional but it looks like cut-and-paste gone wrong:
let us **tus now** → let us **know**
> Cut-and-paste error in "report error" template

- harper-core/src/linting/lint_group.rs
- harper-core/src/linting/mod.rs
- harper-core/src/linting/phrase_corrections.rs
I'm assuming this was a typo or thinko.
"Supposed to" is the correct phrase. "Suppose to" is the error.
References:
- https://grammarist.com/spelling/supposed-to/
- https://english.stackexchange.com/questions/8129/supposed-to-or-suppose-to
- https://quillbot.com/blog/definitions/supposed-to/
- https://www.reddit.com/r/grammar/comments/n171gz/suppose_to_or_supposed_to/
- https://langeek.co/en/grammar/course/1613/suppose-vs-supposed
> bug: reverse correcting "supposed to" to "suppose to"

- harper-core/src/linting/spell_check.rs
When the spellchecker has suggestions you have to click on Quick Fix to see them.
First:  
Second:  
But when `matcher.rs` suggests a fix it tells you directly, without having to click on Quick Fix
So use the same text in spell_check as in matcher when there's only one suggestion.
> feat: if spellcheck only has one suggestion mention it directly

- harper-core/dictionary.dict
- packages/obsidian-plugin/src/index.ts
Fixes #609 by correctly converting between character indexes (used by Harper) and Unicode code point indexes (used by Obsidian).
I may decide to move this logic into `harper.js` later.
> fix(obsidian): correctly handle Unicode conversions

- Cargo.lock
- harper-cli/Cargo.toml
- harper-cli/src/main.rs
- harper-core/src/lib.rs
- harper-core/src/spell/hunspell/mod.rs
- harper-core/src/spell/mod.rs
- justfile
These take an annotated word in the form of a hunspell entry, apply all the affix rules for the annotations, and output all the resulting word forms:
```
% just getforms workspace/1MS
workspace
workspace's
workspaces
% target/debug/harper-cli forms absorber/1MS
absorbers
absorber
absorber's
```
This implements my feature request in #606 
A version of this can be added to an expanded `just addnoun` so the user can confirm that no unexpected forms will be allowed and no legitimate forms will be flagged, before they add the word.
> feat: add `harper-cli forms` and `just getforms`

- harper-core/src/linting/phrase_corrections.rs
Fixes #620 by narrowing the offending linter down to just the incorrect idiom.
> fix(core): make narrow linter specifically for `long and behold`

- harper-core/src/linting/matcher.rs
This is very common in Indian English but I've heard it in Euroenglish as well.
Examples from GitHub:
- Hi, Today after 3 hours, I'm at live YouTube Podcast, **discussing about** Meteor 3 at small devices like Raspberry Pi.
- this repository **discusses about** core concepts in react
Unfortunately there seem to be rare false positives:
- However, I think that raises some similar challenges to what I **discussed about** option 1 above: it creates a pressure to organize the configuration in a way ...
But this sounds wrong in other ways anyway. Better would be "discussed in", "mentioned in", "covered in"...
> feat: Flag "discuss about" instead of "discuss"

- harper-core/src/linting/matcher.rs
Implements #616
Suggests "sooner rather than later" and "sooner or later"
> feat: suggestion to change "sooner than later"

- harper-core/src/linting/matcher.rs
[#505 feat: Flag "would of", "could of", and "should of", etc](https://github.com/Automattic/harper/issues/505)
Supports negative and contracted versions.
> Implements #505 could of, should of, would of -> ... have

- packages/.eslintrc.cjs
- packages/web/src/lib/Editor.svelte
- packages/web/src/lib/Underlines.svelte
Shown in the attached GIF. Note that there are intentionally no animations _after_ the page load is loaded.
https://github.com/user-attachments/assets/75cdd692-540e-4191-81f3-d29005a3f62f
> feat(web): make underlines animate into existence on page load

- harper-core/src/linting/lint_group.rs
- harper-core/src/linting/mod.rs
- harper-core/src/linting/phrase_corrections.rs
I thought "and alike" was only used by non-native English speakers. Not sure whether it was included here as a correct phrase on purpose or by accident.
> fix: change "and alike" phrase correction to "and the like"

- harper-core/dictionary.dict
- harper-core/src/linting/compound_nouns/mod.rs
Fixes #704 by fixing the `someways` dictionary entry that previously declared it a noun.
> fix(core): `someways` is not a noun

- harper-core/dictionary.dict
- harper-core/src/linting/then_than.rs
- harper-core/src/patterns/all.rs
I was writing some documentation and made the mistake of using `then` when I meant `than`, but Harper didn't catch it. I've added some more test cases and allowed the rule to be more general, as well as adding space to define exceptions to the rule.
> feat(core): allow the `ThenThan` linter to cover more cases

- harper-core/src/linting/compound_nouns/general_compound_nouns.rs
- harper-core/src/linting/compound_nouns/implied_ownership_compound_nouns.rs
- harper-core/src/linting/lint_kind.rs
`LintKind::Spelling` should only be used by the spellcheck rule
> Make `Lintkind::Spelling` exclusive to one rule.

- .github/ISSUE_TEMPLATE/report-false-positive.md
- .github/ISSUE_TEMPLATE/report-grammatical-error.md
- Also adds a `false-positive` github issue label
- And adds a 'Potential false positives' section to the template for reporting grammatical errors
> feat: github template for reporting false positives

- harper-core/src/lexing/mod.rs
- harper-core/src/token_kind.rs
Addresses #673
Work in progress since it passes <s>all</s> test but does not fix 673's problem
@elijah-potter I think I'm going to need help with this one. It still fails with "1980s and" but I don't really know how to debug it. I would assume the "number" lexer is matching the "1980" part but "1980s" on its own passes its test... So perhaps "s and" is getting lexed first?
> feat: lex 4-digit plural decades

- harper-core/src/linting/possessive_your.rs
- packages/web/src/routes/docs/about/+page.md
While working on documentation, I found a bug in the `PossessiveYour` rule. I've added a test case for it and modified the rule to work properly.
> fix(core): edge case found in Harper's documentation

- packages/vscode-plugin/package.json
Was left out from the overhaul. Together with #726, should close #667.
> fix(vscode-plugin): update config keys to new standard

- harper-core/dictionary.dict
- harper-core/src/linting/compound_nouns/general_compound_nouns.rs
- harper-core/src/linting/compound_nouns/implied_action_compound_nouns.rs
- harper-core/src/linting/compound_nouns/mod.rs
- harper-core/src/linting/repeated_words.rs
- harper-core/src/linting/then_than.rs
- harper-core/src/patterns/noun_phrase.rs
- harper-core/src/patterns/sequence_pattern.rs
- harper-core/src/token_kind.rs
- harper-core/src/word_metadata.rs
> fix(core): restrict `GeneralCompoundNouns` to ignore adverb prefixes

- harper-core/dictionary.dict
This pr adds the plural of `integration` -> `integrations` to the dictionary. Here are the new expansions of the word:
I thought `reintegrations` and `disintegrations` seem a little weird. `disintegrations` is listed as a plural of `disintegration` on merriam-webster so I think that's fine, but `reintegrations` is not listed as a word. Chat-GPT says it's correct and refers to "multiple instances of something being restored or brought back together", but I'm not sure how reliable that is haha. Opening this as a draft until we can decide.
> feat(core): added plural form of integration

- harper-core/src/lexing/mod.rs
I only [mentioned it in Discord](https://discord.com/channels/1335035237213671495/1335035237213671498/1342765690813157388) when nobody else was active.
On builds straight from master I was seeing the 's' after decades like '1990s' flagged, even though my decade lexer has been merged.
I checked the tests and we only had unit tests looking for edge cases. This adds a positive and a negative test against the sentence mentioned. Let me know if there's a better way to code them or if they belong in some other file. The other lexers in `harper-core/src/lexing/mod.rs` also didn't have any in-context tests.
`cargo test` passes all tests but `just test` gives strange new errors I've never seen before, including creating supposed screenshot png's but those are all blank. I think this is something …
> feat: tests for sentences containing a decade

- justfile
- packages/vscode-plugin/package.json
- packages/vscode-plugin/src/extension.ts
- packages/vscode-plugin/src/tests/fixtures/.vscode/settings.json
- packages/vscode-plugin/src/tests/suite/integration.test.ts
Related to #667 since that's what brought up talks about look and feel.
- Only send Harper specific settings to `harper-ls`. Prior to this change, VS Code sent up the whole user configuration by default. Aside from being the sane thing to do, this helps when debugging messages between VS Code and `harper-ls` since there's less cruft in the logs.
- Change setting key prefixes from `harper-ls` to `harper`. This change only applies to VS Code, the prefixes are changed to `harper-ls` before being sent to `harper-ls`. It's primarily for aesthetic purposes in the Settings UI.
Before, with the awkward Harper-ls:
After, with just the title:
- Manually in the extension host
- `just test-vscode`
> feat(vscode-plugin): config updates

- harper-core/src/linting/pronoun_contraction/should_contract.rs
For some reason, the pattern for the `ShouldContract` rule was looking for nouns, rather than adjectives. This PR corrects that error.
Unit tests, mostly.
> fix(core): improper pattern

- packages/web/src/routes/docs/contributors/environment/+page.md
- packages/web/src/routes/docs/integrations/language-server/+page.md
N/A
This PR updates the documentation website to include instructions for the new `harper-git` AUR package. It also clarifies the difference between `just dev-web` and `just build-web`.
I used `just dev-web` to preview my changes on the development server.
> doc(web): updated environment and language-server documentation on the website

- harper-cli/src/main.rs
- justfile
Modified `harper-cli forms` to accept a space-separated list of annotated words to support this.
`just sample` accepts a numeric argument for how many words to choose from the curated dictionary.
I've already fixed some mistakes with wrong affix annotations in the curated dictionary. This provides a way to check randomly to see if anything looks wrong.
It may actually be more useful for the user dictionary. Let me know if I should add that and suggest names for switches. Another possibility as to also have an option that samples from the combined curated+user dictionaries.
The implementation uses the *nix `jot` command which is included with macOS which does not have `shuf`. Let me know if this solution is broken for Linux etc.
Example:
```bash
% just sampleforms 5
Finished `dev` profile …
```
> feat: add `just sample` to list all forms of random dictionary words

- harper-core/src/lexing/mod.rs
- harper-core/src/lexing/url.rs
No issues. Spotted these things while fixing another issue in the same source file.
Fixed character APIs that checked being numeral instead of checking English (ASCII) digits only:
- `.is_alphanumeric` → `.is_ascii_alphanumeric`
- `.is_numeric` → `.is_ascii_digit`
Use `.is_ascii_hexdigit` instead of manually checking `a-f` etc
I made sure all the existing tests still passed plus I added checks for number parsing, which we didn't yet have.
I expected digits from other alphabets to pass but although they passed the character detection they didn't pass being parsed into floats. Now they are rejected earlier when checking the characters.
For English numbers, I tested integers, decimals, and scientific notation. I included tests for explicitly negative and positive numbers but those tests …
> fix: better ascii and hex digit checks

- harper-core/src/linting/closed_compounds.rs
Resolves #771
I don't believe the `forthwith` rule as actually constructive. For reference, I don't believe LanguageTool covers it. It's not a very common word and there doesn't seem to be a heuristic for it. It's best to just remove it.
> fix(core): remove bad `Forthwith` rule

- harper-core/src/linting/modal_of.rs
#792
Fixes the false positive bug where "might of" should not be corrected to "might have" when "might" is a noun as in "the might of the army" or "the great might of the military"
I added new unit tests for the "the might" and "adj. might" cases.
I added a new unit test with the real-world sentence that led to me to this false positive.
> feat: implement false positive "the great might of"

- harper-core/src/spell/hunspell/mod.rs
N/A
A test that in `dictionary.dict` you can put all the flags after `/` in a single entry even if the word covers multiple homographs and senses - or you can put each on its own line with just the flags relevant to it - and the result will be the same.
This means we can have entries that are self-contained when the affixes and annotations get complicated without fear that it might change functionality.
It only tests that both ways expand to the same set of forms - it doesn't test that all the metadata is the same - a great opportunity for another test!
`cargo test`
`just test`
> test: check that dictionary attributes can be spread over two entries

- packages/web/package.json
- packages/web/src/routes/titlecase/+page.svelte
- packages/yarn.lock
In order to test Harper's title case algorithm, I've created a public page to convert any case text to title case, similar to [titlecaseconverter.com](https://titlecaseconverter.com/).
I've also spent some time making it pretty.
https://github.com/user-attachments/assets/2f633a28-c0ee-4984-87d9-6c56bd1edd97
I've opened and edited the heading on both Firefox and Chrome manually.
> feat(web): create page for debugging the title-case algo

- harper-core/src/linting/phrase_corrections.rs
No issue was filed. It went straight to PR.
When I converted all of the inflections of "to get rid off" to use `phrase_corrections.rs` I neglected to convert the past participle `gotten rid off`.
When I added a test I noticed the other tests were missing their `#[test]` so I added those too.
Other PRs related to this one: #685 and #717 
N/A
Added a new test for the past participle form using a sentence from GitHub.
Did `cargo test` and `just test` and everything passed.
> fix: add missing "gotten rid off" to other "rid off"

- justfile
N/A 
I noticed that `just searchfor` crashed on my machine.
It turned out to be because [ripgrep](https://github.com/BurntSushi/ripgrep) isn't installed in macOS.
I ran into this problem while reading #847 
N/A
Ran it some random words. I don't think there are tests applicable to `just`?
> fix: fall back to `grep` when `rg` is not available

- harper-core/src/linting/phrase_corrections.rs
Fixes #711 and #835
Adds all inflected variants of "change tact/tacts/tacks" and "change of tact/tacts/tacks"
I also changed the wording of the 'description' and 'message' fields.
I added more atomic tests, but not for all combinations and permutations as I realized how many there were.
I added several tests using real-word sentences found on GitHub or the Internet in general.
> feat: add many variants of "change of tact"->"tack"

- .github/workflows/build_harper_binaries.yml
- .github/workflows/package_vscode_plugin.yml
- .github/workflows/release_harper_binaries.yml
- .github/workflows/release_vscode_plugin.yml
#850 
Up until recently, we've been building the Linux binaries on Ubuntu 20.04 (which means they get built with the right GLIBC version). Recently, GitHub has https://github.com/actions/runner-images/issues/11101. I updated the image but neglected to consider this as a side effect. 
Since we're already using `cross` to build our binaries, it should be pretty easy to use it to build against an older GLIBC version (while still using `ubuntu-latest`).
- [Cross' Supported Targets Table](https://github.com/cross-rs/cross#supported-targets)
Since the problem is in our CI, the only way to test is to run the builds here, in GitHub Actions. 
I'll then try running the built binaries inside a local `ubuntu:20.04` Docker container.
> Build against an older GLIBC version

- Cargo.lock
- harper-core/Cargo.toml
- harper-core/src/ignored_lints/mod.rs
- harper-core/src/linting/lint_group.rs
- harper-core/src/linting/mod.rs
- harper-core/src/linting/pattern_linter.rs
- harper-core/src/linting/phrase_corrections.rs
- harper-core/src/linting/proper_noun_capitalization_linters.rs
- harper-core/src/linting/spell_check.rs
- harper-core/src/spell/merged_dictionary.rs
- harper-ls/Cargo.toml
- harper-ls/src/backend.rs
- harper-ls/src/main.rs
- packages/harper.js/src/Linter.test.ts
#472 is now the largest performance problem to address. After the work in this PR, running the Matcher now accounts for 50% of total incremental lint time.
In a private discussion with @nyonson, I was informed that Harper was starting to slow down on one of his larger documents. This was a result of large cache misses (and expensive cache lookups). 
This weekend, I sat down for a few hours to iron them out. As a result, we saw a further 50% improvement on incremental lint times, as well as an improvement to initial lint times (thanks to less expensive cache misses).
Manually on my machine. I'll be adding some more integration tests. In the meantime, @lukasmwerner, would you mind running this branch for your notes? I want to identify any possible configuration problems.
> Cache busting

- .github/workflows/build_harper_binaries.yml
- .github/workflows/release_harper_binaries.yml
**Branch created out of #877.**
This PR adds compilation support for Linux musl. **Depends on #877.**
`cross` supports g++ for musl targets, but the only way to make `actions-rust-cross` successfully compile Harper is to enable `force-use-cross` introduced with v1. After a few hours of headache, I spotted #877 by @elijah-potter which simplified my commit quite well.
N/A
See https://github.com/kiding/harper/actions.
> feat: Added Linux musl compilations

- packages/web/src/routes/docs/integrations/neovim/+page.md
I saw this [comment on Reddit](https://www.reddit.com/r/neovim/comments/1j7ookn/comment/mgz1tb2/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button), which makes me believe this isn't as well documented as it could be.
Added a little example section for Neovim users who want to disable `sentence_capitalization`.
> docs(ls): give example config that disables `sentence_capitalization`

- harper-cli/src/main.rs
N/A
Previously `just getforms` (and `harper-cli forms`) would only expand the affix annotations provided on the commandline. Now it will first check if the word on the commandline is already in the dictionary, if it is annotated there, and if those annotations differ from those provided on the commandline. It will then print the old expansions, new expansions, or both.
See [ficcdaf's comments](https://github.com/Automattic/harper/pull/847#issuecomment-2708414662) in #847 
I manually tried to test every combination of words and annotations already in the dictionary and not, etc.
I'm open to suggestions on adding unit tests.
> Just getforms improvements

- harper-core/src/parsers/markdown.rs
- harper-core/src/parsers/mod.rs
#880
It looks like Harper was omitting the paragraph break after the code block, which meant that it inferred the code block's `Unlintable` token to part of the sentence. This PR make a few tweaks to fix that behavior and adds a test for it.
An additional unit test, as well as manual test shots.
> fix(core): insert paragraph breaks after code blocks

- harper-comments/src/comment_parser.rs
- harper-comments/src/lib.rs
- harper-comments/src/masker.rs
- harper-comments/tests/language_support.rs
- harper-comments/tests/language_support_sources/ignore_comments.c
- harper-comments/tests/language_support_sources/ignore_comments.rs
- harper-core/src/mask/mod.rs
- harper-tree-sitter/src/lib.rs
Still needs some tests. I'm not sure this is the cleanest way to accomplish this, but I based it on a comment @elijah-potter once made about something similar (I think shebangs).
> feat: mask out comments beginning with spellchecker:ignore

- harper-core/src/linting/phrase_corrections.rs
N/A
I just heard "as early back as" for the first time in a YouTube video. It sounded strange to me but I found a few instances on GitHub and many on the rest of the Internet. But it's several orders of magnitude rarer than "as far back as".
- I added an atomic unit test with just this phrase.
- I added a real world unit test with an actual sentence I found on GitHub.
- 28 Sept 2019 — Issue Details. Electron Version: 6.0.10 (but happening **as early back as** 1.x.x and 2.x.x for us).
- skin overrides also supports a wide variety of minecraft versions - **as early back as** 1.14.4. note that only versions since 1.19.4 have the ui, and only ...
- ... **as early back as** the 1930s with The Man Who Awoke. However, the technology has been too expensive for it to really become commonplace. …
> feat: linter for "as far back as" to replace "as early back as"

- harper-core/src/linting/sentence_capitalization.rs
- harper-core/src/punctuation.rs
N/A
I spotted two homophone-spellos in the source:
- carrots are root vegetables
- carets are `^`
- unphased means not in phases
- unfazed means remaining calm in the face of adversity
`cargo test` runs with no failures.
> fix: two spelling mistakes based on homophones

- harper-core/src/linting/lint_group.rs
- harper-core/src/span.rs
The `PatternLinter` cache previously assumed that document chunks would never move. This was incorrect and has been rectified.
Before this PR, lint results would slide around as the document would be modified.
Now they're rock-solid.
> hotfix(core): properly store spans in `PatternLinter` cache

- justfile
#904
I've modified the `just addnoun` script to automatically insert a newline if one is not present at the end of the dictionary.
Manually.
> feat: insert newline automatically in `just addnoun`

- harper-core/src/linting/phrase_corrections.rs
N/A
Just the kind of thing phrase_corrections was intended for. Very common on GitHub:
- This community will help **each and everyone** who is facing issue in opensource and share job opportunities, resources, etc. 
- ... **each and everyone** of them is not a good idea and also just not feasible.
- ... for them to ship it same as they already do for vscode (so that not **each and everyone** has to ...
- Composing a state which can be scoped/pulledback to allow **each and everyone** of them to work off of the same piece of state can prove to be challenging.
- [Is it each and every one or everyone?](https://quillbot.com/blog/frequently-asked-questions/is-it-each-and-every-one-or-everyone/)
- [Is "each and everyone" redundant? - English …
> feat: linter for "each and everyone"

- harper-core/src/linting/phrase_corrections.rs
N/A
I noticed my fingers typing "get ride of" when I wanted to write "get rid of" so I checked GitHub and it's very common, so I'm adding it to the "get rid off" lint.
I added unit tests based on all the variants of "get ride of" or "get ride off" that I could find examples of on GitHub.
> feat: expand the "get rid off" lint to cover "get ride of"

- harper-ls/src/backend.rs
- packages/vscode-plugin/src/extension.ts
- packages/vscode-plugin/src/tests/suite/helper.ts
- packages/vscode-plugin/src/tests/suite/integration.test.ts
Fixes #487. Fixes #382.
This PR restricts `clientOptions.documentSelector` to the `file` and **`untitled` scheme, and changes `load_file_dictionary` to always succeed on the `untitled` scheme.**  This will prevent the non-existent `.git` files from showing up in Problems since they use `gitfs` scheme[^1], **and make Harper work on untitled/unsaved files. `HarperAddToFileDict` should fail as expected.**
VS Code's documentation[^2] suggests there may be other schemes like ~~`untitled`,~~ `http`, `ftp`, etc. Harper never worked with `untitled` with an error saying `ERROR harper_ls::backend: Unable to generate the file dictionary.` Harper's `file_dict_name` assumes `url` is a file path, so this shouldn't break any preexisting feature.
N/A
To test for `untitled`: open a new document, type …
> fix(vscode-plugin): ignore non-existent ".git" files, support untitled/unsaved files on VS Code

- packages/web/src/routes/docs/contributors/environment/+page.md
Cherry-picked from #689
Some Linux users need some previously unmentioned dependencies to run the VS Code integration tests.
> docs: mention hidden library dependencies

- harper-core/src/linting/mod.rs
- harper-core/src/linting/phrase_corrections.rs
Issue: #929
Follows on from my previous PR: #935 
I've introduced a new assertion that improves upon `assert_suggestion_result` to allow for assertions on the `nth` suggestion in a lint.
Existing tests that use `assert_second_suggestion_result` to use it.
> feat(core): create new test assertion for `nth` suggestion results

- harper-comments/src/masker.rs
- harper-comments/tests/language_support.rs
- harper-comments/tests/language_support_sources/ignore_shebang_1.sh
- harper-comments/tests/language_support_sources/ignore_shebang_2.sh
- harper-comments/tests/language_support_sources/ignore_shebang_3.sh
- harper-comments/tests/language_support_sources/ignore_shebang_4.sh
https://github.com/Automattic/harper/issues/65
https://github.com/Automattic/harper/pull/421
This closes #65 and adds four tests. If the approach described in #421 is preferred, I can change it.
```
cargo run --bin harper-cli -- lint harper-comments/tests/language_support_sources/ignore_shebang_1.sh --dialect American
cargo run --bin harper-cli -- lint harper-comments/tests/language_support_sources/ignore_shebang_2.sh --dialect American
cargo run --bin harper-cli -- lint harper-comments/tests/language_support_sources/ignore_shebang_3.sh --dialect American
cargo run --bin harper-cli -- lint harper-comments/tests/language_support_sources/ignore_shebang_4.sh --dialect American
cargo test
```
> feat: ignore shebang lines

- harper-core/dictionary.dict
N/A
Added multi-line comments at each already existing section of the curated dictionary.
Mainly, the original import, the unsorted stuff added by users which may contain very domain-specific terms, the recent import of terms which differ in spelling between US and other regions, my experimental section of multi-word entries that contain spaces or hyphens, and the section at the bottom where `just addnoun` will add new entries with some advice to add manual changes there for users who are a bit uncertain.
I also updated the count at the top of the file to be big enough to contain the current number of entries.
The experimental multi-word section had been separated into two pieces, probably during a merge.
I added two or three more hyphenated terms.
I want to do more cleanup and …
> chore: add comments describing major sections

- harper-ls/src/backend.rs
- packages/vscode-plugin/src/tests/suite/helper.ts
- packages/vscode-plugin/src/tests/suite/integration.test.ts
N/A
When someone changes the language mode of an opened document, Harper does not reflect the change, resulting in erroneous diagnostics. This has become apparent after #927 was introduced since `untitled`/unsaved documents default to auto detect or plain text, unless "Files: Default Language" (`files.defaultLanguage`) is configured.
The LSP specification states:[^1]
> If the language id of a document changes, the client needs to send a `textDocument/didClose` to the server followed by a `textDocument/didOpen` with the new language id if the server handles the new language id as well.
Harper so far has not implemented `did_close`. This PR implements `did_close` by removing the URL from `doc_state`. Sending an empty diagnostic is added since the `updates diagnostics when files are deleted` …
> fix(harper-ls): handle language mode change and VS Code auto detect

- harper-core/dictionary.dict
- harper-core/src/document.rs
- harper-core/src/linting/adjective_of_a.rs
- harper-core/src/linting/lint_group.rs
- harper-core/src/linting/mod.rs
- harper-core/src/token_string_ext.rs
N/A
Flags phrases such as "How slow of a laptop are we talking here?" and suggests removing the "of".
It only flags adjectives in the positive degree (neither comparative or superlative).
It avoid a few hard-coded false positives where the adjective is much more common as a noun in this context.
This is so common, especially in American English, that many people might not know it's an error.
Some references:
- [WordReference](https://forum.wordreference.com/threads/not-that-adjective-of-a-noun.3260438/)
- [English StackExchange](https://english.stackexchange.com/questions/64605)
- [English StackExchange](https://english.stackexchange.com/questions/30011)
- [WordReference](https://forum.wordreference.com/threads/not-that-adjective-of-a-noun.2854358/)
- …
> feat(core): flag "<adjective> of a"

- harper-core/src/linting/multiple_sequential_pronouns.rs
Also fixes #578 and #724.
The list of personal pronouns was not complete and only consisted of 11 words. They were in a haphazard order so hard to check at a glance.
I have now included all 22 personal pronouns and possessive adjectives (which are not pronouns but very commonly mislabeled as pronouns) in the form of a table-like paradigm to ensure it includes all combinations of subject case vs object case, singular vs plural, masculine vs feminine, vs neuter, possessive pronouns, and possessive adjectives.
Some words occur in multiple positions in the paradigm but this is fine since it's much easier to check at a glance to make sure no words are missing, and the result is a `WordSet` that can only contains one copy of each word.
Ideally newer features of `WordMetadata` should be used but …
> fix: include the full set of personal pronouns and possessives

- harper-core/dictionary.dict
N/A
While updating my [syntax highlighter VS Code extension for `dictionary.dict`](https://github.com/hippietrail/harper-dict-syntax) I noticed some lines in red, indicating a syntax error.
On closer inspection I found that had the new `<` annotation flag indicating "American dialect" but did not have a `/` separating the word from the annotations.
As far as I can tell only two entries were affected: `colored's` and `coloring's`
Before:
After:
> fix: 2 words in curated dict lack / before annotations

- harper-core/src/span.rs
- packages/web/src/routes/docs/harperjs/configurerules/+page.md
- packages/web/src/routes/docs/harperjs/spans/+page.md
- packages/web/src/routes/docs/integrations/obsidian/+page.md
- packages/web/vite.config.ts
I've updated documentation for:
- The Obsidian plugin's ability to ignore code blocks
- What a span is in `harper.js`
- Correct use of `LintConfig` in `harper.js`
> Improve doc coverage

- harper-core/src/linting/adjective_of_a.rs
N/A
The false positives were not handled correctly when capitalized at the beginning of a sentence.
I added a new unit test with a capitalized word in the false-positive set.
`cargo test` has zero fails.
> feat: detect capitalized false positives

- harper-cli/Cargo.toml
- harper-cli/src/main.rs
- harper-core/src/word_metadata.rs
N/A
This PR sets American as the default dialect for harper-cli. [The document](https://writewithharper.com/docs/contributors/review#Testing-Using-Cargo-and-harper-cli) and `just dogfood` won't fail right away anymore.
And that's it!
N/A
Manually.
> fix(harper-cli): set American as the default dialect

- harper-core/src/linting/adjective_of_a.rs
N/A
Two more false positives found and handled: "inside of" and "out of".
- I added a unit test for each based on the sentences I found them in.
- `cargo test` succeeds 100%
> feat: more false positives: "inside of" & "out of"

- packages/vscode-plugin/src/extension.ts
#982 
Adds an indicator in the status bar for the English dialect set.
It reflects the **Workspace** setting, which seems to be the default. I don't know VS Code or its extension system deeply enough to know if this is the best solution.
On my setup I was able to confuse myself by changing the dialect in **User**.
Changing the Workspace setting instantly changes the flag, but does not reload the window. Some squiggles seem to be updated instantly, but not all of them.
It is possible to make the indicator clicking to change the setting but I haven't implemented this. It would be best to fully grok the Workspace vs User ramifications before attempting this.
It is possibly to add a Harper logo but not as a PNG or SVG. You need to do some font trickery: …
> Dialect indicator for VS Code extension

- packages/wordpress-plugin/src/harper/Logo.jsx
- packages/wordpress-plugin/src/harper/index.tsx
This PR addresses a bug in the plugin that makes it impossible to open the 'more options' menu in the top-right of the Gutenberg editor.
> fix(wordpress): crashes when options menu is opened

- Cargo.lock
- harper-comments/Cargo.toml
- harper-comments/src/comment_parser.rs
- harper-comments/tests/language_support.rs
- harper-comments/tests/language_support_sources/common.mill
- packages/web/src/routes/docs/integrations/language-server/+page.md
Add support for Scala comment parsing. The `.sbt` extension is for [Scala Build Tool](https://www.scala-sbt.org/), and the `.mill` extension is for [Mill](https://mill-build.org/mill/index.html).
I ran `harper-cli` on a `.scala`, `.sbt`, and `.mill` file (with `./target/release/harper-cli lint -d American <path-to-file>`) and got lints on the comments. Doing the same with released `harper-cli` (installed from Homebrew) gives `Error: Could not detect language ID.`
> feat(comments): add `scala` support

- packages/obsidian-plugin/src/HarperSettingTab.ts
- packages/obsidian-plugin/src/index.ts
This PR adds a new setting to the Obsidian plugin called "delay" that delays linting until a certain amount of time after the user has finished typing. This is to avoid overwhelming the user with erroneous suggestions.
https://github.com/user-attachments/assets/8eee5fc3-eb71-4451-83f9-7bf1e46fb738
Manual testing.
> feat(obsidian): add debounce setting

- harper-core/dictionary.dict
- harper-core/src/linting/adjective_of_a.rs
More false positives handled
A unit test is added for each false positive.
`cargo test` passes.
> Adj of a curation 2025 04 02

- harper-core/dictionary.dict
- harper-core/src/linting/repeated_words.rs
- harper-core/src/word_metadata.rs
N/A
I was considering making some special cases to the 'repeated words' lint for words which are repeated and not an error.
I decided that wasn't needed but while looking at the code I wondered about some of the logic.
There was a special case to ensure `is is` gets flagged.
This would've been due to logic testing words that can be repeated:
1. Homographs - words that are both noun and verb, or pronoun and adjective, etc.
2. Words that have multiple properties within one type of verb.
2 didn't seem right to me. There have been some changes to the affix code relating to parts-of-speech and properties etc. There have also been corrections to `dictionary.dict` with anomalous annotations.
I removed the test for homograph test #2 and the special case for "is" and with the current state of the …
> refactor: remove unneeded logic for repeated words

- harper-core/src/linting/then_than.rs
N/A
Fixes one or two false positives I've spotted with "then" where "than" should be.
I made the logic more linguistically robust around how adjectives and comparison work in English.
In particular "than" can't be used after every adjective, only those inflected into the comparative form (faster), irregular comparatives (worse), and uninflected (positive) adjectives after the special words "more" or "less".
All existing tests pass and I added some I thought up to cover edge cases that either would've failed before, or might not be obvious even if they would've already passed, or for false positives I've spotted in the wild.
`cargo test` passes all tests.
> refactor: improve logic and robustness of then→than

- harper-core/dictionary.dict
- harper-core/src/linting/compound_nouns/implied_instantiated_compound_nouns.rs
N/A
While hunting for why Harper wants to change "impact on US may be limited" to "onus" I first thought "on" being a rare verb was responsible.
I tweaked odditties in the the dictionary annotations that caused both "on" and "us" to be marked as verbs.
But it turned out the reason for that problem was not a verb to the left of the compound but to the right of the compound.
So I adjusted the linter message to include the verb responsible and thus clear for both users and developers.
(The surprising suggestion for "onus" still happens, that will be separate.)
`cargo test` and clippy are still happy.
> feat: mention which verb triggered lint in msg

- harper-core/src/linting/possessive_your.rs
N/A
I've been noticing for some time that Harper always flags "you guys" to change into "your guys". This PR treats that as a special case exemption.
I added a unit test based on a sentence in my test data.
`cargo test` and `cargo clippy` are satisfied.
> feat: exempt "you guys" from the possessive your linter

- harper-core/src/linting/an_a.rs
- harper-core/src/linting/phrase_corrections.rs
N/A
While looking into adding an "and" suggestion to the "a/an" linter I saw the typo "trail and error". This turns out to be common, so here's a lint.
Added the comment from the "a/an" linter as a unit test.
`cargo test`
> feat: trail and error→trial and error

- harper-core/src/linting/lint_group.rs
- harper-core/src/linting/sentence_capitalization.rs
#77 
Some "words" are not usually uppercased when they're first in a sentence. I introduce two heuristics to identify them:
1. Proper nouns which are usually trademarks
iOS, macOS, iMac, npm, etc.
3. Any word that in its dictionary form starts with a lowercase letter and has at least one uppercase letter (before any apostrophe, hyphen, or space (though only the first is currently possible)
mRNA, dB, eSIM, fMRI, kHz, kW, kWh
I added unit tests for each case using real-world sentences.
`cargo clippy` ` cargo test` `just test`
> feat: Add special cases to sentence capitalization

- harper-core/src/linting/compound_nouns/implied_ownership_compound_nouns.rs
N/A
The heuristic that checks for possible split compound nouns following possessives has a false positive after `let's` that I often see triggered while testing Harper on YouTube transcripts.
This is because `let` is a noun as well as a verb, but in real life it's very rarely used in the possessive.
So we check for this one word specifically before flagging.
I added a unit test based on the sentence that brought this to my attention this time.
> feat: don't allow "let's" to trigger a following compound

- README.md
- packages/web/src/routes/+page.svelte
- packages/web/src/routes/docs/about/+page.md
- packages/web/src/routes/docs/contributors/author-a-rule/+page.md
- packages/web/src/routes/docs/contributors/visual-studio-code/+page.md
- packages/web/src/routes/docs/faq/+page.md
- packages/web/src/routes/docs/integrations/emacs/+page.md
- packages/web/src/routes/docs/integrations/helix/+page.md
- packages/web/src/routes/docs/integrations/language-server/+page.md
- packages/web/src/routes/docs/integrations/neovim/+page.md
- packages/web/src/routes/docs/integrations/visual-studio-code/+page.md
- packages/web/vite.config.ts
None in particular
These are updates based on pain points I've seen on issues and discussions or undocumented new features.
> Documentation updates

- packages/harper.js/docs.sh
None
I was going around the Harper website and noticed that the links to subpages in `/docs/harperjs/ref` were broken, so I fixed that here.
Along the way, I also improved the `docs.sh` script:
- Refactor a bit and prevent printing unnecessary errors. Mainly the "cannot remove `./html`" one.
- Generate standalone HTML pages with proper meta titles and descriptions instead of partials. A plus of this is we get some syntax highlighting for free.
- Use a Pandoc Lua filter when changing `.md`s to `.html`s in links instead of Perl. This is more robust as we're sure that it'll only specifically change link `href`s that end in `.md`.
- Use Pandoc's default document styling instead of MVP.css. This one is just personal preference and I'm open to revert it if you don't like it. I just find that …
> `harper.js` API reference generation improvements

- harper-core/src/linting/phrase_corrections.rs
N/A
I just heard somebody say "hone in on" instead of "home in on" on YouTube.
I checked to make sure "home" is the correct variant and this PR fixes all verb forms: hone, hones, honing, honed.
I found an example sentence for each inflected verb form and made a unit test for each one.
`cargo test` passes 100%.
> feat: hone in on→home in on

- harper-core/src/linting/modal_of.rs
N/A
A YouTube transcript I was testing Harper on had the text 
> ... for now you could of
> Course put ...
It flagged "could of"
But then I noticed the "of" really was part of "of course" and there was no error.
This PR fixes that so that "of Course" will also be identified as a false positive.
I added two mixed-case tests. One to catch "could of" and one to make sure "could of course" is not caught.
> fix: make modal-of linter case insensitive

- harper-core/dictionary.dict
- harper-core/proper_noun_rules.json
- harper-core/src/linting/adjective_of_a.rs
#1066 
As well as moving "StackOverflow" and "StackExchange" to "Stack Overflow" and "Stack Exchange" I've added "stack overflow". I've also added capitalization rules for the first two under a new heading "Companies, Products, and Trademarks".
There are also the usual new words and adjustments to annotations I do while dogfooding on YouTube transcripts.
I've accidentally added curation of the "adjective of a" linter into this PR, so if I find any more false positives I'll add those in here too.
> Fix bug 1066 "Stack Overflow", dictionary curation, adjective-of-a curation

- harper-core/src/linting/adjective_of_a.rs
N/A
"off of a" should probably be subject to a linter dealing with "based on" / "based off" / "based off of" but it's not related to this linter. Nobody ever says "That's so very off of a switch."
Added a unit test based on the context in which I found this false positive.
> chore: "off of a" false positive

- harper-core/src/linting/phrase_corrections.rs
N/A
Another odd variant I heard for the first time today which is actually already pretty common.
Dictionaries say we avoid something "like the plague" but younger speakers have been avoiding things "like a plague".
- https://dictionary.cambridge.org/dictionary/english/avoid-like-the-plague
- https://www.collinsdictionary.com/dictionary/english/avoid-someone-or-something-like-the-plague
- https://www.oxfordlearnersdictionaries.com/definition/english/avoid#avoid_idmg_1
- https://www.merriam-webster.com/wordplay/avoid-like-the-plague-origin
I added another set of phrase corrections to this PR. Correcting the simple past tense form used to construct the perfect tenses of "to go"
- have went → have gone
- had went  → had gone
- having went → having gone
I added a unit test for each one based …
> feat: phrase corrections: like a plague, have went, case and point, aswell

- harper-core/dictionary.dict
- harper-core/src/linting/compound_nouns/general_compound_nouns.rs
- harper-core/src/linting/compound_nouns/implied_ownership_compound_nouns.rs
- harper-core/src/linting/lets_confusion/let_us_redundancy.rs
- harper-core/src/linting/lets_confusion/mod.rs
- harper-core/src/linting/lets_confusion/no_contraction_with_verb.rs
- harper-core/src/linting/pronoun_contraction/should_contract.rs
- harper-core/tests/run_tests.rs
But doing so has a snowball effect on other tests!
May try to tackle: #470 #752 
Tackles false positives and other problems related to mixing up
let / lets / let's / let us
One problem was flagging `let`/`lets` to be replaced by `let's` if the next word is a verb, but there were many false positives caused by words which are both nouns and verbs.
Unfortunately simply ruling those out had flow-on effects in other lints or other tests.
I've commented out some of those tests and added comments about the problem.
Some may be able to be re-enabled if heuristics are devised to disambiguate whether such words are really verbs or nouns.
I've also added comments to explain how some of the existing logic works and renamed some identifiers I felt impeded clarity.
I've added a bunch of unit tests for …
> feat: handle some false positives in let/lets/let's/let us

- harper-core/src/linting/phrase_corrections.rs
#467
Flags forms/tenses of "have past" and suggests changing to "have passed"
I added a unit test for each verb form harvested from GitHub.
There are likely to be false positives for this one but it was hard to gather enough info on which specific kinds would be common to work out a heuristic in advance.
> feat: have past→have passed

- packages/vscode-plugin/package.json
- pnpm-lock.yaml
#1074 
This is the lowest-common-denominator to work with both VS Code forks, Cursor which is at 1.96.2 and Windsurf which is at 1.97.0
I build (from Windsurf) using
`just setup` and `just package-vscode`
Then I installed the resulting VSIX manually from the command palette into both Windsurf and Cursor.
The status bar item with the dialect indicator and the new Harper logo showed up in both. Typing gibberish into the editor of both causes Harper to flag them as misspellings.
> fix: reset vscode version to `1.96.2`

- harper-core/src/linting/phrase_corrections.rs
N/A
Fixes both using the comparative instead of the superlative, and using a space between the first two words or a hyphen between the last two.
I've added on lint for each combination of wrong word and hyphen vs space, all from sentences found on GitHub.
> feat: worse-case scenario→worst-case scenario

- harper-core/src/linting/phrase_corrections.rs
N/A
Flags the now-common "incase" and suggests writing it as two words "in case".
I added a unit test based on an example fished out of GitHub.
> feat: incase→in case

- harper-core/src/patterns/sequence_pattern.rs
N/A
Just a little quality-of-life addition for `PatternLinter` coders. Whitespace is very minor and often between all the words in a pattern.
So just as 'then any capitalization of' has the `t_aco()` shorthand this introduces a `t_ws()` shorthand to allow patterns to be more expressive in less space.
Added a unit test for all of `aco()`, `t_ws()`, and `t_aco()`
> feat: adds a `t_ws()` shorthand for `then_whitespace()` in the spirit of `t_aco()`

- packages/obsidian-plugin/src/HarperSettingTab.ts
- packages/obsidian-plugin/src/index.ts
Part 2 of fixing #982
Next to the Harper logo/button in the status bar the country code and flag for the selected dialect are now displayed.
These update when the dialect setting is changed.
Manual testing.
> feat: implement dialect indicator for Obsidian plugin

- harper-core/src/linting/phrase_corrections.rs
N/A
I noticed the phrasing "client's side" in something I was reading and it didn't sound right. It turned out using "client's side" is really common, probably because it makes sends and sounds almost exactly the same as "client-side". "Server's side" instead of "server-side" isn't quite as common but is also out there.
My browser also flags these: 
There are likely false positives when the context is not client-server computing and sometimes even in this context.
Perhaps "client side" and "server side" should also be suggested but the only style opinion I could find preferred the hyphenated version no matter where in the sentence.
Added a unit test for each based on sentences mined from GitHub.
> feat: client's side→client-side, server's side→server side

- harper-core/src/patterns/indefinite_article.rs
`IndefiniteArticle` wrapped its internal `WordSet` into a `SequencePattern` for some reason. This doesn't change its behavior and strictly adds overhead for no reason. This PR removes the superfluous `SequencePattern`.
No change in behavior. Existing tests suffice.
> Removed the useless `SequencePattern` in `IndefiniteArticle`

- harper-core/src/patterns/mod.rs
Fixes #1137
In #1124, I accidentally changed the `Pattern` trait to always be `Send + Sync`, which caused compiler errors if the `concurrent` feature wasn't set.
It hasn't been.
> fix: Make code compile without `concurrent` feature

- harper-core/src/document.rs
N/A
- `get_token_offset()` allows you to look in either direction from a document index iterator. Since `get_token()` takes a `usize` you had to first check if you were going to look before index 0, whereas looking past the end would just return None.
- With `get_token_offset()` you'll get a Token or None in either direction.
- Having a base and an offset lets you incrementally step further bit by bit in either direction from an index to get more context for disambiguation heuristics.
- `get_next_word_from_offset()` takes this a bit further since often such heuristics require sequences of words separated by whitespace. Now you can pass the offset from your iteration index to the whitespace and this will check both that whitespace then continue to the next word, returning `None` if either …
> feat: `Document` QoL functions for tokens & words

- harper-core/src/linting/phrase_corrections.rs
N/A
At least on YouTube everybody now says "invest into" but it's still very far behind the traditional "invest in".
"Invest in" is in some professional dictionaries: [cambridge](https://dictionary.cambridge.org/dictionary/english/invest-in), [merriam-webster](https://www.merriam-webster.com/dictionary/invest%20in); but "invest into" isn't yet.
I added a unit test for each inflection based on sentences found on GitHub.
> feat: invest into→invest in

- harper-ls/src/backend.rs
Fixes #466
This adds a hard-coded limit to the filesize accepted by `harper-ls`. We might want to add a config option for this. I don't know of anyone that would use it, though. Let me know if that would be useful to you.
> fix(core): runaway `harper-ls` processes

- harper-core/src/lexing/mod.rs
Fixes #1010
I don't think it makes sense in pretty much any context to parse a terminating dot as part of a number.
For example, the sentence: `The I like the Switch 3.` 
Additional unit tests.
> fix(core): don't lex the last period as part of a number

- harper-core/src/linting/correct_number_suffix.rs
- harper-core/src/linting/linking_verbs.rs
- harper-core/src/linting/number_suffix_capitalization.rs
This PR provides some brief documentation to linters that currently incorrectly reuse documentation from the `LongSentences`  linter.
> docs: fix incorrect documentation for some linters

- harper-core/src/linting/no_oxford_comma.rs
- harper-core/src/linting/oxford_comma.rs
- harper-core/src/linting/pattern_linter.rs
- harper-core/src/patterns/mod.rs
I added an `iter_matches` method to patterns which returns an `impl Iterator<Item = Span>`. It works exactly as `find_all_matches`, but without allocating a `Vec<Span>`.
I did this, because I noticed that 3 linters re-implemented the logic from `find_all_matches`. Using the iterator API, everything can now use the same implementation.
It's tested by all existing tests.
> feat: iterator API for pattern matches

- README.md
Fixes a grammar mistake and applies some minor rephrasing in the *Performance Issues* section of the README. I'm not 100% sure the rephrasing is beneficial, so I put it into its own commit (I'm stuck in analysis paralysis at this point 😅).
> docs(readme): fix grammar and minor rephrasing

- harper-core/src/linting/dashes.rs
This PR modifies the `Dashes` linter to prevent it from suggesting multiple lints for a single long sequence of hyphens. Previously, if you had a line of 60 hyphens, you would get 20 lints suggesting you replace each triple hyphen with an em dash. With these changes, only a single lint will be provided (encompassing the whole sequence).
While working on these changes, I noticed it can be very difficult if not impossible to visually discern between en and em dashes in some contexts. To reduce the potential for confusion, I extracted the dash literals into module-level `const`s. This did require making some of the tests more verbose with `format!`s though, so there is a tradeoff. I'm certainly open to undoing or modifying this "const extraction" if it's deemed to be detrimental.
- `cargo …
> feat(core): avoid providing multiple lints for a single long hyphen sequence in `Dashes`

- harper-core/src/patterns/mod.rs
Fixes #1183 
The non-concurrent settings were still using `Option<NonZeroUsize>` but elsewhere had been changed to `Option<usize>`. Easy Fix! 
Clicked on various `Run` buttons in various source files in Windsurf.
> fix: running individual tests was broken

- harper-core/dictionary.dict
Related to https://github.com/Automattic/harper/issues/243, regression to fix the former in https://github.com/Automattic/harper/commit/ec345e7591861c585ab37b34a6cdc34ccdaf2486.
From the CLI lint.
**Before**:
```
Advice: 
╭─[foo.md:1:1]
│
2 │ Did you hear about Tree-sitter? It definitely isn't spelled Treesitter.
│                                                             ─────┬────  
│                                                                  ╰────── Did you mean to spell “Treesitter” this way?
```
**After**:
```
Advice: 
╭─[foo.md:1:1]
│
2 │ Did you hear about Tree-sitter? It definitely isn't spelled Treesitter.
│                                                             ─────┬────  
│                                                                  ╰────── Did you mean …
```
> chore(harper-core/dictionary): add Tree-sitter

- harper-core/src/linting/possessive_your.rs
N/A
Prevent flagging "showing you what's available".
I'm not generalizing yet until we have more data, just treating "what's" as special for now.
I also tweaked the description wording a little.
While I was there I change another commented-out test to use `#[ignore]`
I added a unit test using the sentence that revealed the false positive.
> fix: add exception to possessive_your linter

- harper-ls/src/dictionary_io.rs
#1169 
This PR makes it so we sort the words iterator when saving the dictionary to disk. Thereby writing a sorted dictionary.
This uses the [default ordering for strings](https://doc.rust-lang.org/std/primitive.str.html#impl-Ord-for-str), which means the resulting sort won't necessarily be alphabetic.
Tested by using the code action to add to the global dictionary from Neovim. Running `sort -c` showed the dictionary file was properly sorted after adding a word. After an initial sort, adding a word no longer produced unreasonably large diffs in the dictionary file.
> feat(ls): write sorted dictionaries

- harper-core/dictionary.dict
- harper-core/src/linting/mod.rs
- harper-core/src/linting/spell_check.rs
- harper-core/tests/text/tagged/Alice's Adventures in Wonderland.md
- harper-core/tests/text/tagged/Computer science.md
- harper-core/tests/text/tagged/Part-of-speech tagging.md
- harper-core/tests/text/tagged/The Great Gatsby.md
N/A
I merged, sorted, and commented new dictionary contributions.
I noticed that `afterwards` was being flagged even for Australian English where it's the preferred spelling.
- Fixed annotations for both `afterward` and `afterwards`
- Added tests for American vs Commonwealth dialects
I had trouble getting some tests to work with Australian English despite this. It turns out that the `dialect` field of the metadata is a string and can only hold one dialect. Changed to simpler tests, some of which are set to ignore with notes.
Added +ive and -ive unit tests for `afterward` and `afterward` for each dialect. Two are disabled due to the above limitation.
> feat: dictionary curation and dialect tests

- harper-core/dictionary.dict
n/a
Adds the -able suffix form to allow "manufacturable", adds a new common noun "favicon" (https://developer.mozilla.org/en-US/docs/Glossary/Favicon, https://en.wikipedia.org/wiki/Favicon). Favicon isn't in the dictionary per-se but I think it common enough to warrant adding?
Before:
```
Advice: 
╭─[foo.md:1:1]
│
1 │ That is manufacturable.
│         ───────┬──────  
│                ╰──────── Did you mean “manufacture”?
2 │ Did you add that favicon to the website yet?
│                  ───┬───  
│                     ╰───── Did you mean “falcon”?
───╯
```
After: (nothing)
n/a
> chore(harper-core/dictionary): add manufacturable and favicon

- harper-core/src/linting/how_to.rs
N/A
While dogfooding I noticed sentences like "How did you do that" were flagged by the `HowTo` linter so I added a special exception.
I added a unit test with the sentence that revealed the problem.
All tests pass.
> fix: exception for "how did you" in how-to linter

- harper-core/proper_noun_rules.json
- harper-core/src/linting/phrase_corrections.rs
- harper-core/src/linting/proper_noun_capitalization_linters.rs
N/A
- adds "Guilded Age" and "once and a while" phrase corrections
- adds Gilded Age proper noun capitalization correction
It turns out that the current capitalization code for phrase corrections capitalizes letters in the output string at the same *indices* as the input string, not the first of each word and not matching which words in the canonical string started with an uppercase letter.
This means `Guilded Age` gets transformed to `Gilded aGe` and `guilded age` gets transformed to `gilded age`.
I believe this may be fixed as part of @RunDevelopment 's upcoming `PatternLinter` PR.
I added unit tests based on sentences from GitHub for each phrase and variants.
The ones that are not uppercased are commented out with explanatory comments.
> feat:Guilded Age→Gilded Age; once and a while→once in a while

- harper-core/src/lexing/mod.rs
- harper-core/src/linting/inflected_verb_after_to.rs
- harper-core/src/linting/it_is.rs
- harper-core/src/linting/lets_confusion/mod.rs
- harper-core/src/linting/phrasal_verb_as_compound_noun.rs
- harper-core/src/linting/possessive_your.rs
- harper-core/src/linting/sentence_capitalization.rs
- harper-core/src/linting/spell_check.rs
- harper-core/src/spell/mutable_dictionary.rs
N/A
I just discovered that Rust tests allow a `#[ignore]` attribute that has an optional 'reason' field. I wasn't aware of so this before so now I've gone ahead and converted all commented-out tests to use it.
`cargo test` is still happy.
> chore: convert commented out tests to use `#[ignore]`

- Cargo.lock
- harper-ls/Cargo.toml
- harper-ls/src/main.rs
- justfile
- packages/obsidian-plugin/package.json
- packages/obsidian-plugin/rollup.config.mjs
- packages/obsidian-plugin/src/index.ts
- packages/web/src/routes/latestversion/+server.ts
- pnpm-lock.yaml
We often have to confirm Harper versions when we debug problems with rules. This PR sets `harper-ls` and the Harper Obsidian plugin to print both the current version and the latest version (from GitHub) to the console.
Manual testing.
> Print version numbers

- packages/chrome-plugin/src/Box.ts
- packages/chrome-plugin/src/Highlights.ts
- packages/chrome-plugin/src/LintFramework.ts
- packages/chrome-plugin/src/TextFieldRange.ts
- packages/chrome-plugin/src/background/index.ts
- packages/chrome-plugin/src/computeLintBoxes.ts
There are no specific GitHub issues related to this PR. It fixes problems found through my own dogfooding.
There were some problems with grammatical errors being underlined outside the render box of `<textarea />` elements. They also did not follow any internal scroll.
This PR fixes both problems.
Manual testing.
> fix(chrome-ext): render on scroll

- harper-core/src/parsers/mod.rs
- harper-core/src/patterns/mod.rs
- harper-core/src/sync.rs
I found the `LSend` trait today and used it to simplify the trait definitions of `Pattern` and `Parser`
I just made sure that everything compiles. I also checked that tests runs.
> refactor: use `LSend` trait to simplify trait definitions

- harper-core/dictionary.dict
- harper-core/tests/text/tagged/Alice's Adventures in Wonderland.md
"towards" [is a preposition](https://en.wiktionary.org/wiki/towards#Preposition), but it was incorrectly tagged as noun plural.
See snapshots.
> fix: "towards" is a preposition

- harper-core/src/patterns/exact_phrase.rs
Use the `PlainEnglish` rather than the `Markdown` parser in `ExactPhrase::from_phrase`.
`SimilarToPhrase::from_phrase` already uses the `PlainEnglish` parser. I could well be wrong since I'm not too familiar with this part of the code, but I don't think we want to be parsing our phrases as markdown. A quick look through the callers of this function did not seem to indicate any need for markdown parsing.
(I noticed this when tinkering with `harper-cli` and seeing that the `Markdown::parse` function was being called multiple times even when parsing a file with the `PlainEnglish` parser.)
Quite possibly not well enough.
`cargo test` shows all tests still pass successfully.
I briefly tested `harper-ls` and `harper-cli` with the changes. I wasn't able to notice any new issues.
> perf(core): `PlainEnglish` parser in `ExactPhrase`

- harper-ls/src/dictionary_io.rs
Adds a test to ensure we write stably sorted dictionaries with the current sort method. Though the limited word count might not cover every edge case, it should ensure we don't accidentally do something like write unsorted dictionaries or reverse the sort order in the future.
(Also adds some `const`s and a test utility function to hopefully make it easier to write `dictionary_io` tests in the future.)
Related PR: #1195 
`cargo test`, making modifications until the test was passing successfully.
> test(ls): ensure we write sorted dictionaries

- harper-core/src/linting/phrasal_verb_as_compound_noun.rs
I noticed that Harper crashed with the following error:
```
thread 'main' panicked at harper-core\src\linting\phrasal_verb_as_compound_noun.rs:54:17:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The VSC language server then repeatedly restarts and crashes until the following message pops up:
The crash was caused by an `unreachable!` statement being very reachable. The dictionary contains some multi-word entries, which contain hyphens and spaces. The tokenizer seems to use this information to parse words like "add-on" as one token. This triggered the following code path:
```rs
// * Can't contain a hyphen or space.
if nountok_charsl.contains(&'-') || nountok_charsl.contains(&' ') {
// This means Harper's …
```
> fix: prevent crash in PhrasalVerbAsCompoundNoun

- harper-core/dictionary.dict
- harper-core/tests/text/tagged/Alice's Adventures in Wonderland.md
- harper-core/tests/text/tagged/Computer science.md
- harper-core/tests/text/tagged/Part-of-speech tagging.md
- harper-core/tests/text/tagged/The Constitution of the United States.md
- harper-core/tests/text/tagged/The Great Gatsby.md
According to wikionary, "of" can have the meaning of "have" in [Eye dialect](https://en.wiktionary.org/wiki/Appendix:Glossary#eye_dialect), a dialect of deliberate misspelling. Given how common the word "of" is in English, I believe it is more important to unambiguously tag "of" as a preposition than to support a deliberate misspelling. This will help prevent false positives in rules dealing with verbs.
See snapshots.
> fix: Remove verb property from "of"

- harper-core/src/linting/lets_confusion/no_contraction_with_verb.rs
Solves issue #1202
The phrasing in the bug report is inherently ambiguous even looking forward more and more tokens.
However, `lets go` is a very common mistake for `let's go` so worth flagging even though in a context like `he lets go of the ball` would an error. On the other hand `let go` is more likely to be part of a context like `he let go of the ball` that a mistake for `let's go`.
So this boils down to a frequence heuristic.
Which means false positives and negatives are still possible but less likely now.
I've also applied some refactoring I've learned to clean up the other code a little.
I made a unit test from the sentence in the screenshot in the issue.
> fix: heuristic for no-contraction-with-verb for "let go"

- harper-core/src/linting/lets_confusion/no_contraction_with_verb.rs
- harper-core/tests/pos_tags.rs
N/A
While reading new and old code in Harper I spotted some typos in comments.
> chore: minor typos in two files' comments

- packages/obsidian-plugin/src/index.ts
This PR updates the Obsidian plugin to pretty-print the `LintKind` in the suggestion popup. It is subtle, but important.
Before:
After:
Manually. See above.
> fix(obsidian): pretty-print the lint kind

- harper-core/tests/linters.rs
- harper-core/tests/pos_tags.rs
- harper-core/tests/snapshot.rs
- harper-core/tests/text/linters/Alice's Adventures in Wonderland.snap.yml
- harper-core/tests/text/linters/Computer science.snap.yml
- harper-core/tests/text/linters/Part-of-speech tagging.snap.yml
- harper-core/tests/text/linters/The Constitution of the United States.snap.yml
- harper-core/tests/text/linters/The Great Gatsby.snap.yml
Why I added snapshots:
1. They make it easy to see the impact of changes to lints (if the text corpus is large enough).
2. Changes in the tokenizer, dictionary, or PoS tagger that affect lints will also (likely) become visible.
3. It becomes easy to see when the span of a report is suboptimal/wrong.
Similar to the PoS tag snapshots, I added snapshots for the reports of all lints. Just like before, snapshots are automatically created and updated just by running the snapshot test.
Snapshots are formatted in a YAML-like syntax, and reports have a Rust-error-messages like syntax. Example:
```yml
Lint:    Spelling (63 priority)
Message: |
46 | calculator in 1623. In 1673, Gottfried Leibniz demonstrated a digital mechanical
|                              ^~~~~~~~~ Did you mean to spell …
```
> test: add snapshots for linters

- harper-core/src/patterns/nominal_phrase.rs
Related to #1226 
This PR introduces a helper function in the test section of `nominal_phrase.rs` that allows assertions on matching a sequence of strings.
Currently tests are opaque as you have to compare the results against a collection of numbers which represent offsets into a slice of `Token`s but use `Span`, which is documented as representing a slice of `char`s.
See related issue #1226
One function used `dbg!` to output the resulting set of spans. I left it in but added a debug to also output the set of strings. If either or both of these should go, let me know.
All tests still pass. I didn't introduce any new tests but converted the ones using numbers to use strings.
For instance:
```rs
#[test]
fn complex_apple() {
let doc = Document::new_markdown_default_curated("A red apple with …
```
> Nominal phrase test helper

- harper-core/src/linting/long_sentences.rs
- harper-core/tests/text/linters/Alice's Adventures in Wonderland.snap.yml
- harper-core/tests/text/linters/Computer science.snap.yml
- harper-core/tests/text/linters/Part-of-speech tagging.snap.yml
- harper-core/tests/text/linters/The Constitution of the United States.snap.yml
- harper-core/tests/text/linters/The Great Gatsby.snap.yml
Found by looking through #1228 
This PR changes the `LongSentences` lint to emit lints whose spans start at the first word, not the space before.
Look at the snapshot tests to see the difference in output.
> fix(core): long sentence lint should start with word

- harper-core/src/linting/phrasal_verb_as_compound_noun.rs
`message` was only ever assigned `Option::Some` values, so I removed the unnecessary `Option` wrapper.
Hasn't been.
> refactor: remove unnecessary Option in PhrasalVerbAsCompoundNoun

- harper-core/src/linting/pattern_linter.rs
I didn't like that `run_on_chunks` allocates a new `Vec` for every chunk with a lint in it. So I made it return an iterator instead.
This doesn't change the behavior of Harper in any way.
Hasn't been.
> refactor: don't allocate when linting chunks

- harper-core/src/linting/an_a.rs
- harper-core/tests/text/linters/The Great Gatsby.snap.yml
I found that `AnA` incorrectly assigned "utterly" the article "a". In this PR, I changed the heuristic for guessing articles to fix this.
See tests.
Existing tests cover this.
> fix: fix indefinite article for "utter(ly)"

- harper-core/src/linting/phrase_corrections.rs
N/A
Also handles plural.
Also converted two commented-out tests to use `#[ignore]`
I added 3 unit tests using sentences sourced from GitHub.
One is `ignore`d though due to the way Harper tries to preserve the case of the original by uppercasing letters at specific indices instead of applying title case if the original used title case.
> feat:definitive article→definite article

- packages/obsidian-plugin/src/index.ts
- packages/obsidian-plugin/src/lint.ts
Created in #1240
In #1240, an odd amount of padding was introduced around the lint message. This PR returns it to the original amount of padding by assigning `<p />` tags the same properties as the `<span />`s that previously occupied that space.
Before: 
After:
Manually.
> fix(obsidian): odd padding around message

- harper-core/src/linting/spell_check.rs
- harper-core/src/spell/mod.rs
- harper-core/tests/text/Spell.md
- harper-core/tests/text/linters/Alice's Adventures in Wonderland.snap.yml
- harper-core/tests/text/linters/Difficult sentences.snap.yml
- harper-core/tests/text/linters/Part-of-speech tagging.snap.yml
- harper-core/tests/text/linters/Spell.snap.yml
- harper-core/tests/text/linters/The Constitution of the United States.snap.yml
- harper-core/tests/text/linters/The Great Gatsby.snap.yml
- harper-core/tests/text/tagged/Spell.md
- packages/vscode-plugin/src/tests/suite/integration.test.ts
The fix for some dialect-based misspellings is very obvious. E.g. color ↔ colour and recognize ↔ recognise. So I changed the spell checker to **only** suggest the version of the word in the current dialect, if it detects an "ou↔o" or "s↔z" misspelling.
I also refactored and slightly optimized `SpellCheck::cached_suggest_correct_spelling`. It now only caches the words that will be suggested (without any excess) and generally works a bit more efficiently.
See tests.
Using existing tests and a new document.
> feat: improve spell check suggestions by accounting for common misspellings

- harper-core/src/linting/phrase_corrections.rs
N/A
"Adieu" is a German word meaning farewell but it's become common for people to use it in place of the English word "ado" which means "fuss". I usually only occurs in a couple of contexts, so we can use `phrase_corrections`.
- further ado
- much ado
I added a unit test for each variant using a sentence found on GitHub.
> feat: adieu→ado

- harper-core/src/linting/phrase_corrections.rs
N/A
In a Facebook post I noticed somebody wrote "a fare bit". A fare is the price of a ticket. The expression should be "A fair bit" meaning "A decent amount".
I checked and found it on GitHub too. Sometimes missing the "a".
I added a unit test using a sentence found on GitHub.
> feat: a fare bit→a fair bit

- harper-core/dictionary.dict
- harper-core/src/linting/lets_confusion/no_contraction_with_verb.rs
- harper-core/tests/text/linters/The Great Gatsby.snap.yml
- harper-core/tests/text/tagged/Alice's Adventures in Wonderland.md
- harper-core/tests/text/tagged/Computer science.md
- harper-core/tests/text/tagged/Difficult sentences.md
- harper-core/tests/text/tagged/Part-of-speech tagging.md
- harper-core/tests/text/tagged/The Constitution of the United States.md
- harper-core/tests/text/tagged/The Great Gatsby.md
- harper-core/tests/text/tagged/this and that.md
N/A
The logic was broken probably because it was hard to follow.
A false positive with "let in" was being flagged.
I removed the `4` verb flag from `in` in `dictionary.dict` which was due to obsolete senses.
I fixed the broken logic and improved the comments so the logic should be easier to follow in the future.
I added a new test case for the false positive I found and fixed.
I made sure all existing tests still passed after improving the logic.
> fix: fix logic and improve explanatory comments

- harper-ls/src/backend.rs
- harper-ls/src/config.rs
- harper-ls/src/dictionary_io.rs
- harper-ls/src/ignored_lints_io.rs
- harper-ls/src/io_utils.rs
- harper-ls/src/main.rs
- packages/web/src/routes/docs/integrations/language-server/+page.md
#1220
This PR allows `harper-ls` users to persist lint ignores across sessions. This works by saving the relevant context hashes to the data directory on the system—similar to how we handle file dictionaries.
I've also taken the opportunity to refactor some of the now-shared logic between ignored lints and file dictionaries.
This has been tested manually.
> feat(ls): persist lint ignores

- packages/obsidian-plugin/src/lint.ts
#1268
I've moved the `max-height` rule lower in the tree to avoid interfering with other plugins that instantiate tooltips.
It does not seem to negatively affect Harper's layout at all. 
Manually.
> fix(obsidian): move `max-height` css rule lower in the tree

- harper-ls/src/pos_conv.rs
(Hopefully) fixes #1253 
This PR primarily seeks to resolve the crash mentioned in the aforementioned issue. The crash was caused because `position_to_index` would return an incorrect index of `0` as the `end` in `range_to_span` when processing the input mentioned in the issue. (The problematic position being `Position { line: 1, character: 0 }`.)
As I struggled to fully understand it, I opted to rewrite the `position_to_index` method. I was not able to find the desired/defined behavior of this method within documentation (particularly for edge-cases), so I conjured what I could from the existing tests.
The proposed new `position_to_index` uses a sort of "saturating" arithmetic. That is, if the requested line index is OOB, the last character of the `source` is returned. If the requested …
> fix(ls): fix `position_to_index`

- harper-core/src/linting/compound_nouns/implied_ownership_compound_nouns.rs
- harper-core/tests/text/linters/Alice's Adventures in Wonderland.snap.yml
- harper-core/tests/text/linters/The Great Gatsby.snap.yml
N/A
I had noticed for some time that `a very` was sometimes flagged and the suggested fix was `Avery`.
I finally investigated and the context was after `that's`, which the `implied_ownership_compound_nouns` linter treated as a possessive when it's actually a contraction.
While checking things out I realized the special case for `let's` only worked with the straight typewriter apostrophe but not the curved typography apostrophe. I added apostrophe and case normalization before checking the special case exceptions.
This fixed a couple of lints in the snapshots too.
Before: 
After: 
I added a unit test for `that's` and a second one for `let's` that used the curved apostrophe: `let’s`.
> fix: 'a very' no longer flagged to change to 'Avery'

- harper-core/src/linting/most_number.rs
N/A
I heard somebody saying "maximum amount of" in a YouTube video and realized that should be among the suggestions for "most number of".
I added a new unit test based on the sentence that inspired this improvement.
> feat: add "maximum amount" and "maximum number" to suggestions

- harper-core/src/linting/a_part.rs
- harper-core/src/linting/lint_group.rs
- harper-core/src/linting/mod.rs
#468
Tries to fix "apart" used when "a part" is correct and "a part" when "apart" is correct.
Some cases are too difficult to disambiguate correct vs incorrect so far, those are still flagged but the message also advises when to leave it without "correcting".
I added a bunch of tests, some made up for simple cases, some mined from GitHub for real-word examples.
I also added comments with other sentences from GitHub where I couldn't even figure out what they were trying to say.
> feat: correct mixing up "apart" and "a part"

- harper-core/src/linting/adjective_of_a.rs
- harper-core/tests/text/linters/Alice's Adventures in Wonderland.snap.yml
- harper-core/tests/text/linters/Computer science.snap.yml
- harper-core/tests/text/linters/Difficult sentences.snap.yml
- harper-core/tests/text/linters/Part-of-speech tagging.snap.yml
- harper-core/tests/text/linters/The Great Gatsby.snap.yml
N/A
As pointed out by @elijah-potter the list of adjectives that caused false positives was getting unwieldy and gave the impression it would grow forever.
Instead we'll check for a small set of adjectives known to commonly occur in this construction.
Additionally I've identified more specific contexts it's very often used in that makes false positives much less common, but there's still a couple we blacklist.
The contexts are:
- as adj of a
- how adj of a
- that adj of a
- this adj of a
- too adj of a
Of these, "this" looks more likely to produce false positives, so we'll have to keep an eye and in the worst case may have to remove it from the list.
I added a bunch of new tests, most using sentences from GitHub.
I removed on questionable test which was failing but was probably …
> refactor: reduce false positive blacklist with new logic

- harper-core/benches/parse_demo.rs
- harper-core/src/linting/sentence_capitalization.rs
- harper-core/tests/text/linters/Alice's Adventures in Wonderland.snap.yml
- harper-core/tests/text/linters/Computer science.snap.yml
- harper-core/tests/text/linters/Difficult sentences.snap.yml
- harper-core/tests/text/linters/The Constitution of the United States.snap.yml
- harper-core/tests/text/linters/The Great Gatsby.snap.yml
It can sometimes be hard to click on just first letter in the word to fix its capitalization.
This PR changes the offending linter to span the entire first word, making it easier to select and fix.
Manually. Plus, the existing tests pass.
> feat(core): make sentence capitalization replace whole word

- harper-core/src/linting/lint_group.rs
N/A
While trying to learn how to start using `lint_group` I noticed that the rules were partly but not fully alphabetized. And then I noticed the `TheHowWhy` rule was added twice! Once as a struct and once as a pattern. I'm surprised that didn't upset clippy or anything else.
`cargo test` still has no failures.
> chore: sort and dedup lint group rules

- harper-core/dictionary.dict
- harper-core/tests/text/linters/Alice's Adventures in Wonderland.snap.yml
- harper-core/tests/text/linters/Computer science.snap.yml
- harper-core/tests/text/linters/Difficult sentences.snap.yml
- harper-core/tests/text/linters/Part-of-speech tagging.snap.yml
- harper-core/tests/text/linters/The Constitution of the United States.snap.yml
- harper-core/tests/text/linters/The Great Gatsby.snap.yml
- harper-core/tests/text/tagged/Alice's Adventures in Wonderland.md
#1307 
All missing vocab suggested by @ubitux in #1307 has been added along with the usual new words and affix fixes.
One important fix was that the entry for `aluminum` was missing the `<` flag for American English and only had the `@` flag for Canadian English. But it still gets flagged as wrong since the Canadian flag comes first and the metadata system currently only supports one dialect per entry even though the dictionary format supports multiple.
Manual testing against the specific vocab in #1307
> Dictionary curation 2025 05 21

- harper-core/src/linting/nominal_wants.rs
#1291 part 1.
I made "that" a special case because it can be at least two kinds of pronoun.
When "that" is a demonstrative pronoun it acts like a 3rd person and would take the "wants" form of the verb.
But when "that" is a relative pronoun it works with any grammatical number so either "want" or "wants" can come after it.
Since we can't realistically check if `that` is demonstrative or relative, or at least we don't do so yet, we will just not check it for agreement with the verb.
Before: 
After: 
I added a unit test using the sentence from #1298
> fix: solve part 1. of #1298 by making "that" a special case

- harper-core/src/linting/pronoun_knew.rs
2. in #1298
One type of pronoun is the "indefinite pronoun", including: "everything", "something", "nothing"
At least these three indefinite pronouns work before adjectives: "something old, something new".
These three rarely refer to people or animate entities that can be the subject of the verb "to know".
Before: 
After: 
I used the OP's example from their issue as a new unit test.
> fix: solve part 2. of #1298 by allowing indefinite pronouns before "new"

- harper-core/src/linting/phrasal_verb_as_compound_noun.rs
Fixes 3. in #1298
Fixes #1280
Solve part 3. of #1298 by checking if the compound noun is part of a list with other nouns by checking if there's a previous word that's a conjunction and a previous word to that that's a noun.
I also replaced the older custom helper functions and logic with the newer helpers I added to `Document` a couple of weeks ago.
It turned out that #1280 belongs here too. In that case the word before our focus is OOV (out of vocabulary, meaning novel, not in our dictionary). Such words are most often nouns so we treat those just like noun and a noun before a noun is legit: `neovim plugin` so we don't flag those now.
1298 Before: 
1298 After: 
1280 Before: 
1280 After: 
I added a new unit tests using the sentences of each OP.
> fix: solve part 3. of #1298 if it's following a noun+"and" it's probably a compound noun

- harper-core/dictionary.dict
Adds 'togglable' to the curated dictionary by adding the `B` affix onto 'toggle'.
- `cargo test`
- Compiling and manually testing `harper-ls`.
> chore: add 'togglable' to curated dict

- Cargo.lock
- harper-ls/Cargo.toml
- harper-ls/src/backend.rs
- harper-ls/src/config.rs
- harper-ls/src/diagnostics.rs
- harper-ls/src/document_state.rs
- harper-ls/src/io_utils.rs
- harper-ls/src/main.rs
- harper-ls/src/pos_conv.rs
`tower-lsp-server` is a community fork of `tower-lsp`, which appears to be unmaintained.
This fixes https://github.com/Automattic/harper/issues/139 (thanks to https://github.com/tower-lsp-community/tower-lsp-server/commit/5ac6bceb6d6283c3b7d101b32ca25a0f0a4c0b0e, which landed in `tower-lsp-server` v0.21.0).
Unfortunately, this wasn't a drop in replacement. `tower-lsp-server` has made some changes, and also depends on a completely different url/uri library. Here are the relevant changes:
- `tower-lsp-server`: https://github.com/tower-lsp-community/tower-lsp-server/blob/v0.21.1/CHANGELOG.md
- `lsp-types`'s url/uri change: https://github.com/gluon-lang/lsp-types/commit/e3d0ed287e85bc453d7f77a7c9e6d39620b8d1ef
`cargo test` passes, and I have manually tested that I can start/stop harper.
> fix: use community maintained fork of tower-lsp

- harper-core/src/linting/phrase_corrections.rs
N/A
I noticed somebody using "as of lately", did a search, and it seems to be common. Should be "as of late".
Unit test using a sentence from GitHub.
> feat: as of lately→as of late

- packages/vscode-plugin/src/tests/suite/helper.ts
- packages/vscode-plugin/src/tests/suite/integration.test.ts
- packages/vscode-plugin/src/tests/suite/languages.test.ts
#1001
It has been a constant headache testing `vscode-plugin` since it's not quite easy to detect when VS Code actually finished updating diagnostics. #200 simply added a sleep function, but #1004 show it becomes problematic as the project gets complicated.
After some dabbling, it was clear to me that VS Code doesn't provide any API to detect it. The APIs don't provide any access to extension logs or intercept LSP response, which is understandable. It does provide the `languages. onDidChangeDiagnostics` listener, but it wasn't particularly useful since 1) it gets fired strangely too many times, 2) still not possible to detect when it stops, 3) sometimes doesn't get triggered at all. 
In this PR, `waitForDiagnosticChange` simply compares diagnostics before an action and after. It simply …
> fix(vscode-plugin): make test reliable with `waitForDiagnosticChange`

- harper-ls/src/main.rs
#1211
In #1204, we set up a system that breifly connects to `https://writewithharper.com` to get the latest Harper version, printing it alongside the current Harper verison. This happens to make debugging via logs easier when we don't have access to the full system.
This PR introduces a command-line flag for `harper-ls` (`--skip-version-check`) that skips this connection. 
Manually.
> feat(ls): allow skipping the version check

- harper-ls/src/backend.rs
#1331
This PR changes `harper-ls`' behavior to skip the emission of diagnostics on save. Harper will still emit diagnostics on file change (and others), just not on save. 
Since VS Code (and others) block saving until diagnostics are received, this was causing noticeable productivity slowdowns when using the Harper VS Code Extension.
I will be dogfooding this while working today.
> fix(ls): do not emit diagnostics on save

- harper-ls/src/backend.rs
- harper-ls/src/config.rs
- packages/vscode-plugin/package.json
- packages/web/src/routes/docs/integrations/emacs/+page.md
- packages/web/src/routes/docs/integrations/helix/+page.md
- packages/web/src/routes/docs/integrations/language-server/+page.md
- packages/web/src/routes/docs/integrations/neovim/+page.md
Closes #1310
This PR makes the max document length configurable. Currently, it is set to a hardcoded limit of 120,000 bytes.
I have tried to update the documentation to reflect this change in all the relevant areas, however, it is possible that I missed some places. In addition, I'm not 100% confident that the updates I made to the documentation are technically correct, as I am not familiar with the configuration syntax of all our supported clients. I am also not sure if the changes I've made in `packages/vscode-plugin/package.json` are correct.
- `cargo test`
- `just precommit`
Brief manual testing with VS Code and Neovim indicated that the feature works as expected. `harper-ls` would stop providing lints when the file was larger than the max length, and would resume when the file was …
> feat(ls): configurable max length

- harper-core/src/linting/phrase_corrections.rs
N/A
Fixes a typo in the message for the `SufficeItToSay` linter.
I went with
```
`Suffice it to say` is the more standard and more common variant.
```
but it could have also been fixed by changing it to:
```
`Suffice it to say` is more standard and more common.
```
Read it again after fixing it. Then fixed it again (-:
> fix: missing `the` from `SufficeItToSay` message

- harper-core/src/linting/phrase_corrections.rs
N/A
While dogfooding I noticed a misleading message for a "worse/worst case scenario" lint since it fixes both "worse" instead of "worst" and also adds the hyphen between "worst" and "case" if it's missing.
Before: 
After: 
Dogfooded on the same file. As can be seen in the screenshots.
> fix: different messages for wrong word vs missing hyphen

- harper-core/src/linting/nominal_wants.rs
N/A
I noticed a false positive in `nominal_wants.rs` so this fixes it.
Before: 
After: 
I added a whole bunch of unit tests for the variants I could think of using sentences sourced from GitHub.
> fix: false positives after object case pronouns

- harper-cli/src/main.rs
N/A
Just a little tool to list all the compound word variants from the dictionary, as long as there is either an open or hyphenated variant it will then also be able to find the closed variants.
Can be helpful when working on compound noun linters and finding good examples to use in unit tests.
```
Variants for 'checkout':
- check out
- checkout
Variants for 'cleanup':
- clean up
- cleanup
Variants for 'closedcircuit':
- closed-circuit
- closed circuit
Variants for 'comeback':
- come back
- comeback
Variants for 'companywide':
- company-wide
- companywide
```
Manual testing. It will be used to make tests for linters though.
> feat: `harper-cli compounds` command

- harper-core/src/linting/phrase_corrections/mod.rs
- harper-core/src/linting/phrase_corrections/tests.rs
N/A
Sorts the new phrase correction linters into alphabetical order.
As a bonus we can see that there are `IAm` and `IAmAgreement` linters which do different things.
All tests still pass.
> chore: re-sort phrase corrections

- packages/web/src/routes/docs/faq/+page.md
- packages/web/src/routes/docs/integrations/firefox-extension/+page.md
- packages/web/vite.config.ts
#1224
This PR updates the FAQ to direct people to our Firefox integration, as well as adding a special page for the Firefox extension.
> docs: add page for Firefox + update FAQ

- harper-core/src/expr/reflexive_pronoun.rs
- harper-core/src/linting/shoot_oneself_in_the_foot.rs
N/A
Replaces the `new` ctor with `standard` and `with_common_errors` ctors, much like those for `inflection_of_need` and `inflection_of_want` in #1423 
Unit tests have been added to make sure the nonstandard reflexive pronouns like `hisself` and `theirselves` work with the `with_common_errors` ctor and do not work with the `standard` ctor.
> feat: make including bad forms optional

- harper-core/src/linting/phrase_corrections/mod.rs
- harper-core/src/linting/phrase_corrections/tests.rs
N/A
A friend suggested I make a linter for "on route" and research revealed people also use "in route" and that both "en route" and "en-route" are correct.
It turns out that "on route" / "in route" on their own would very often be false positives but that "en route" is most often followed by "to", so the linter actually only checks for "on route to" / "in route to" and will have some false negatives, mostly at the end of sentences.
In a YouTube video I heard somebody say "as it so happens" which sounded wrong to me. I did some checking and it is indeed a new 21st century error for "as it happens".
"As it so happens" is surely a result of cross-pollinating "it so happens" and "as it happens" but the linter doesn't suggest "It so happens" since that's probably context dependent and would …
> feat: as it so happens→as it happens / on route→en route

- packages/chrome-plugin/src/contentScript/index.ts
#1459 
We cannot ignore fields with `spellcheck=off` without significantly impairing Harper's ability to help.
> fix(core): we cannot respect `spellcheck="off"`

- harper-cli/Cargo.toml
- harper-cli/src/input.rs
- harper-cli/src/main.rs
Allows source/input text to be passed directly as a command line argument for some `harper-cli` commands.
This includes: 
- `lint`
- `parse`
- `spans`
This should hopefully make it easier to debug short snippets of text, as it would no longer be necessary to first place them into a file. For instance, it makes it possible to run `lint` like so: `harper-cli lint 'This is an example sentence'`.
This also upgrades `harper-cli` to Rust 2024 (from 2021).
Manual testing of the modified commands.
> feat(cli): allow direct text (non-file) input

- packages/chrome-plugin/src/Highlights.ts
- packages/chrome-plugin/src/background/index.ts
- packages/chrome-plugin/src/editorUtils.ts
Fixes issue with `x.com` from #1395.
Erroneous newlines were being inserted due to the highlight host's proximity to the text's DOM nodes. I've moved them to be adjacent to the Draft.js editor itself.	
Manually.
> fix(chrome-ext): properly place highlights relative to Draft.js root

- Cargo.lock
- harper-cli/Cargo.toml
- harper-cli/src/annotate_tokens.rs
- harper-cli/src/main.rs
- harper-pos-utils/src/upos.rs
Adds a harper-cli command to annotate tokens. This should hopefully make it easier to view and analyze the way we parse tokens. My primary motivation for this was to make it easier to view how certain sentences are parsed via the POS tagger. To the best of my knowledge, currently the only way to get this information is via the `parse` command, whose output (unless processed externally) is not very human-readable.
Though this currently only supports UPOS annotations, I tried to make this command as easily extensible as possible. To add a new annotation method, one would just have add the respective variant to `AnnotationType`, and add that variant to the match statement in `Annotation::from_token()`.
Some potential improvements include:
- Allowing `AnnotationType` to contain …
> feat(cli): add `annotate-tokens` subcommand

- harper-core/src/linting/lint_group.rs
Revealed while reviewing #1555 
I realized some macros in `lint_group.rs` were not properly documented. This makes their function clearer, as well as instructing rule authors on when to use each one.
> doc(core): document `lint_group` macros

- harper-core/src/linting/of_course.rs
- harper-core/src/linting/phrase_corrections/mod.rs
- harper-core/src/linting/phrase_corrections/tests.rs
N/A
Linting the READMEs of trending GitHub repos I noticed "ofcourse" only flagged as a spelling mistake, despite us having a linter for "of course".
In fact it turns out we have two of them, so I also added comments linking the 2 `of course` linters. The standalone one that handles "of curse" and "of corse" ⇔ this phrase corrections one that handles "off course", "o course", and now "ofcourse".
I added a unit test with the first example found on GitHub.
> fix: add ofcourse→of course phrase correction

- harper-core/src/linting/phrase_set_corrections/mod.rs
- harper-core/src/linting/phrase_set_corrections/tests.rs
#525
Add two more phrase set corrections to `WorseOrWorst` for "get worse" and "become worse" in all verb inflections.
Note that I've spotted one source of false positives: "I am **getting worst accuracy** on the same dataste and 3 different models."
In this case "worst" can be an adjective paired with the noun "accuracy" just as well as it can be an adverb paired with "getting".
If this turns out to be common we would want to split this one out into an `ExprLinter` that takes the following word into account to disambiguate.
I've included an `#ignore`d test with this pointed out in a comment.
A unit test has been created for each variation sourced from GitHub.
> feat: get worst→get worse; become worst→become worse

- harper-core/src/linting/phrase_corrections/mod.rs
- harper-core/src/linting/phrase_corrections/tests.rs
#1586
Seems this linter only flags false positives. See the linked issue thread.
Rather than move the linter from `phrase_corrections` to an `ExprLinter` it seems best to just remove it.
I also sorted a couple more recently added lints in `phrase_corrections` alphabetically.
> fix: remove `ThereIsAny` linter, sort others

- harper-core/src/linting/phrase_corrections/mod.rs
- harper-core/src/linting/phrase_corrections/tests.rs
N/A
I noticed "like as if" for the first time yesterday. After some Googling it seems it can always be replaced by either "like" or "as if" and I didn't spot any false positives.
Includes a unit test using a sentence from GitHub.
> feat: like as if→like / as if

- harper-core/src/linting/amounts_for.rs
- harper-core/src/linting/noun_instead_of_verb.rs
- harper-core/src/linting/phrase_set_corrections/mod.rs
- harper-core/src/linting/phrase_set_corrections/tests.rs
N/A
I came across somebody saying "rise the question" on YouTube and found that we already lint it, but only for "rise" and "rises".
The adds "rose", "risen", and "rising" the question, with examples from the internet used in unit tests.
> feat: remaining inflections of rise the question→raise

- harper-core/src/linting/phrase_corrections/mod.rs
- harper-core/src/linting/phrase_corrections/tests.rs
N/A
I just saw a typo in our Discord that Harper doesn't catch:
- If it's important, **go ahead an** open an issue so we can track implementation progress.
This turns out to be very common and since I found no non-typo occurrences of "ahead an" I just made it a `phrase_correction` after "ahead".
I added a unit test based on the above sentence.
> feat: ahead an→ahead and

- harper-core/dictionary.dict
- harper-core/src/linting/noun_countability.rs
- harper-core/tests/text/linters/The Great Gatsby.snap.yml
- harper-core/tests/text/tagged/Alice's Adventures in Wonderland.md
- harper-core/tests/text/tagged/Computer science.md
- harper-core/tests/text/tagged/Difficult sentences.md
- harper-core/tests/text/tagged/Part-of-speech tagging.md
- harper-core/tests/text/tagged/Spell.US.md
- harper-core/tests/text/tagged/The Constitution of the United States.md
- harper-core/tests/text/tagged/The Great Gatsby.md
- harper-core/tests/text/tagged/this and that.md
N/A
Marked mass nouns that came up in a PR review.
Updated the noun countability test to treat OOV similar to noun so as not to flag "Chinese lorem ipsum" after marking "Chinese" as a mass noun.
All tests now pass again.
> chore: marking mass nouns

- harper-core/src/linting/phrase_set_corrections/mod.rs
- harper-core/src/linting/phrase_set_corrections/tests.rs
N/A
Add "investment into" to the "invest into" linter.
But not "investments into" since that results in too many false positives.
I added a unit test using a sentence found on GitHub.com
> chore: add "investment into" to the "invest into" linter

- harper-core/src/span.rs
Some minor code-quality changes in `harper-core/src/span.rs`.
Though not the intended purpose of this PR, the changes in `Span::try_get_content()` also seem to improve performance on the benchmarks by about 1-2% on my machine.
I'm not 100% on removing the assert in `Span::contains()`. I removed it because other similar methods did not have such asserts, and placing such range checks in other methods of `Span` would likely have a noticeable impact on performance. In lieu of removing it, maybe it would be better to instead do the range check as a `debug_assert!`, and place similar debug asserts in other relevant `Span` functions? Or alternatively, make all the `Span` fields private, and do such checks in the constructor and mutator functions only?
- `cargo test`
> refactor(core): span refactorings

- packages/chrome-plugin/src/Highlights.ts
- packages/chrome-plugin/src/PopupHandler.ts
- packages/obsidian-plugin/.gitignore
#1643
It looks like #1643 was caused by the Warframe page itself: upon receiving an input event, it would create a new one without stopping propagation of the old. To solve this, I just filtered out any input calls that happen within 10 milliseconds of the original.
Manually.
> fix(chrome-ext): filter out erroneous double-clicking

- packages/chrome-plugin/src/SuggestionBox.ts
Just as the title says: this PR makes the suggestion box for the Chrome extension fade in, rather than just appear spontaneously.
> feat(chrome-ext): fade suggestion box in

- harper-core/src/linting/that_than.rs
Fixes #1663
"number that" is no longer considered be "more numb than" and is not flagged.
Does not attempt to detect the rare cases when "number" does actually mean "more numb".
I added the sentence from the issue as a new unit test.
> fix: solve that/than false positive

- harper-core/src/linting/phrase_corrections/mod.rs
I recently came across Harper, and while source-diving, found a small typo in the message for the `AfterAWhile` phrase correction. I'm actually not familiar with Rust, but it's only some text, so I hope I did everything correctly 😅.
It hasn't — but it doesn't seem like this message is asserted against anywhere.
> fix(core): typo in phrase correction message

- packages/chrome-plugin/src/Highlights.ts
- packages/chrome-plugin/src/editorUtils.ts
Should address #1690
In my manual testing, problems in the Ghost editor appeared only due to improper positioning of the Harper highlight elements in the DOM. This PR represents a simple fix for that.
Manually.
> fix(chrome-ext): properly position highlights in Ghost editor DOM

- harper-cli/src/input.rs
- harper-core/src/char_string.rs
- harper-core/src/document.rs
- harper-core/src/lexing/url.rs
- harper-core/src/linting/back_in_the_day.rs
- harper-core/src/linting/correct_number_suffix.rs
- harper-core/src/linting/inflected_verb_after_to.rs
- harper-core/src/linting/of_course.rs
- harper-core/src/linting/oxford_comma.rs
- harper-core/src/linting/phrasal_verb_as_compound_noun.rs
- harper-core/src/linting/sentence_capitalization.rs
- harper-core/src/linting/spell_check.rs
- harper-core/src/linting/throw_rubbish.rs
- harper-core/src/parsers/markdown.rs
- harper-core/src/patterns/nominal_phrase.rs
- harper-core/src/spell/dictionary.rs
- harper-core/src/spell/fst_dictionary.rs
- harper-core/src/spell/merged_dictionary.rs
- harper-core/src/spell/mod.rs
- harper-core/src/spell/mutable_dictionary.rs
- harper-core/src/title_case.rs
- harper-core/tests/linters.rs
- harper-ls/src/config.rs
- harper-pos-utils/src/chunker/cached_chunker.rs
- harper-pos-utils/src/tagger/brill_tagger/mod.rs
- harper-typst/src/lib.rs
Fixes #1707
If the LSP client does not provide any mechanism to determine the root of the workspace, we need to resolve things relative to the current directory, but previously we tried that as `.` which it turns out `.try_resolve_in()` does not like.
This changes the behaviour to always `.canonicalize()` the root of the workspace so that subsequent path resolution starts from an absolute path.
N/A ?
The original poster of #1707 confirmed that this fixed their issue.
> fix: canonicalize workspace_root in configuration

- harper-core/src/linting/phrasal_verb_as_compound_noun.rs
N/A
Now checks if the compound noun is part of a larger compound.
For instance: "backup file".
New unit tests added based on text from GitHub repos.
> fix: false positives in phrasal verb to compound noun

- packages/obsidian-plugin/logo-disabled.svg
- packages/obsidian-plugin/src/index.ts
Add a "disabled" version of the logo for the Obsidian plugin.  Display either the normal enabled or the disabled version of the logo in the status bar depending on if Harper's editor linter is enabled or not.
Add a "disabled" version of the logo for the Obsidian plugin.  Display either the normal enabled or the disabled version of the logo in the status bar depending on if Harper's editor linter is enabled or not.
Validated image changes correctly when toggling either from the status bar or from the command palette command.
- [ x ] I have performed a self-review of my own code
> Add a "disabled" version of the logo for the Obsidian plugin.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/report-false-positive.md
- .github/ISSUE_TEMPLATE/report-grammatical-error.md
- .github/ISSUE_TEMPLATE/suggest-a-feature.md
N/A
I've noticed that many of the GitHub templates are unnecessarily wordy.
The PR one and the regular Bug report one were OK but I chopped the others down.
If you feel I've cut out something essential or just gone too far, please give feedback!
> chore: simplify / minimalize github templates

- harper-core/src/span.rs
fixes #1785
Told serde to ignore the span_type in span when de-serializing data.
This seems like the approach to me, unless Harper uses the span struct in a way I am not aware of this should not cause any issues. The reason I believe the issue is on Harper's side is due to the [lsp specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_executeCommand) mentioning that the lsp server needs to communicate CodeAction.command.arguments to the client. This is being done but one of the arguments (the span_type) is not a type that can be returned (as far as I know) by most lsp clients.
Therefore, it will not be returned which causes harper to reject the response.
I ran it locally and connected to the lsp and no longer got the lsp log …
> Neovim code action does not hide Harper diagnostic #1785 fix

- packages/obsidian-plugin/src/HarperSettingTab.ts
- packages/obsidian-plugin/src/State.test.ts
- packages/obsidian-plugin/src/State.ts
#1580 and #1786
I've added two buttons to the settings page of the Obsidian plugin. 
1. Allows you to toggle all rules (as described in #1786)
2. Allows you to reset all rules to their default value.
I've also updated the UI to reflect that described in #1580, which is hopefully more intuitive.
Manually.
> feat(obsidian): change how default values are displayed

- harper-core/src/linting/open_compounds.rs
N/A
Yet another often wrongly compounded pair of words: `upto` should be `up to`.
I include a unit test using the sentence from GitHub that brought this to my attention.
> feat:upto→up to

- harper-core/src/linting/phrase_set_corrections/mod.rs
- harper-core/src/linting/phrase_set_corrections/tests.rs
#525 
I found another case where "worse" is often used mistakenly instead of "worst".
I added "at worse" to `phrase_set_corrections`
I included a unit test with a sentence found on GitHub.
> feat:at worse→at worst

- harper-core/src/linting/noun_countability.rs
N/A
I noticed myself type "a punctuation" and it felt wrong so I added support to the `noun_countability` linter to add the custom countable "punctuation mark" but suppress the standard "piece of punctuation".
I used the sentence I noticed this in for a new unit test.
> feat:a punctuation→a punctuation mark

- packages/chrome-plugin/src/ProtocolClient.ts
- packages/chrome-plugin/src/background/index.ts
- packages/chrome-plugin/src/options/Options.svelte
- packages/chrome-plugin/src/protocol.ts
@lukasmwerner suggested this while at WordCamp US
This PR adds a button to our options page to export the list of enabled domains. @lukasmwerner suggested we have this to more rapidly expand our "official" list of supported domains. Users can save and submit these lists to us, which we can commit to the code.
Manually.
> feat(chrome-ext): export enabled domains

- harper-core/src/expr/sequence_expr.rs
- harper-core/src/linting/how_to.rs
Closes #1492
Harper was falsely flagging to add "to" between "how" and "Microsoft":
I fixed that by adding proper noun to the list of POS not to match.
I also cleaned up the logic with a new `SequenceExpr` QoL helper function.
I then found #1492 with other sentences this linter failed on. I cleaned up the logic further to do away with the verb progressive test. The only kind of verb form that can be used after "to" is the "lemma", (known simplistically as the "present tense").
The functionality for checking for the lemma form of verbs is currently broken until #1730 gets merged. Until then I've added a rough hack that just checks for the `-s`, `-ed`, and `-ing` endings that non-lemma forms of regular verbs end with.
Linting the same position of the same file after the fix goes straight …
> fix: false positive from #1492 and new one with proper noun

- packages/obsidian-plugin/src/HarperSettingTab.ts
- packages/obsidian-plugin/src/State.ts
- packages/obsidian-plugin/src/index.ts
Restore Harper linter active/inactive status between sessions.
Also added an 'Activate Harper' option in settings as one more way to enable or disable Harper's active state.
Tested closing and opening Obsidian vault with and without the current Harper state being enabled to validate current state is restored between sessions.
Tested toggling the new 'Activate Harper' setting to validate it successfully changes the Harper active state and the status bar indicator.
> Restore Harper linter active/inactive status between sessions.

- harper-core/src/linting/lint_kind.rs
N/A
<s>I noticed 4 `LintKind`s were missing from `LintKind::fn new_from_str()`
It seems the function is not used anywhere, so let me know if the better fix is to remove it.</s>
Unused `new_from_str` removed.
All tests still pass.
> fix: missing `LintKind`s from `LintKind::new_from_str`

- packages/chrome-plugin/src/Highlights.ts
- packages/chrome-plugin/src/background/index.ts
Add `core.trac.wordpress.org` to the list of allowed domains for the Harper Chrome plugin.
It seems to work:
[I edited a comment and it discovered a typo I was able to fix through the dialog.](https://core.trac.wordpress.org/ticket/50161?action=comment-diff&cnum=31&version=1)
Brief testing in the browser.
> Add core.trac.wordrpess.org support to Chrome extension

- harper-typst/src/typst_translator.rs
- harper-typst/tests/run_tests.rs
- harper-typst/tests/test_sources/issue_1926.typ
Closes #1926
- Adds an `parbreak()` function that returns a paragraph break token with an empty span
- Adds an `isolate(inner)` function that wraps the inner parse in paragraph breaks
- Uses `isolate` function to isolate the interior of a content block
Using `harper-cli` to verify the parse, and with the following test expecting 1 lint:
```typst
No No
#table(
columns: 2,
[No], [No],
)
```
> fix(#1926): isolate typst content blocks with parbreaks

- harper-core/src/linting/phrase_corrections/mod.rs
- harper-core/src/linting/phrase_corrections/tests.rs
- harper-core/src/linting/phrase_set_corrections/mod.rs
- harper-core/src/linting/phrase_set_corrections/tests.rs
- packages/vscode-plugin/package.json
I've added a rule that looks for common double-negatives and corrects them to encourage clarity. I'm mostly interested if this is reasonable from a philosophical perspective. _Should_ Harper include this?
> feat(core): add rule for unnecessary double-negatives

- harper-core/src/linting/quite_quiet.rs
Fixes #1971
I added "actually" and "really" to the list of exceptional adverbs that can be used correctly before "quite" as well as before "quiet".
A unit test has been added that has all of the bug report's sentences in it.
> fix: adverbs that can come before "quite"

- harper-core/src/linting/somewhat_something.rs
N/A
While dogfooding on the READMEs of trending GitHub repos the way it flagged `somewhat of a cult data structure` struck me as maybe a bit vague and maybe a bit opinionated?
On checking the linter, the `description` didn't even seem to describe what the linter tries to do.
Current `message`: "Use the traditional form."
Proposed `message`: "Consider using `something of a` in more formal writing."
Current `description`: "When describing a single instance of a noun, use `something` rather than `somewhat`."
Proposed `description`: "Flags the phrase `somewhat of a` in favor of `something of a`, which can be considered more traditional."
Historically "somewhat of a" has been in use for a long time even though some dislike and avoid it. So I didn't want to call it "ungrammatical" or …
> docs: improve message and description for `SomewhatSomething`

- .github/ISSUE_TEMPLATE/suggest-a-feature.md
N/A
The Markdown format for checkboxes needs list format apparently.
This PR fixes the ones in the GitHub feature request template to work that way as used elsewhere.
With broken format:
With fixed format:
Manually
> fix: format of checkboxes was broken in feature request template

- harper-core/src/linting/phrase_corrections/mod.rs
- harper-core/src/linting/phrase_corrections/tests.rs
N/A
Watching Tsoding's video that just came out, I quickly noticed two problems we don't yet handle.
- besides the point - instead of beside the point - which I had never heard before
- don't can - instead of can't/cannot - which is pretty common in non-native speakers
I added a snippet from the YouTube transcript as a unit test for each one.
> feat:besides the point→beside the point, don't can→can't

- harper-core/src/linting/nominal_wants.rs
Closes #2010
I identified this issue thanks to the new "organized lints"! 🎉
Also my first PR from behind the GFW! 🥳
I changed from allocating a `String` to doing all string comparisons directly on the `&[char]`.
The replacement wasn't using `replace_with_match_case`.
The logic for determining whether the pronoun and verb already matched for case, person, and number wasn't quite right.
I added a new unit test using the text from the bug report.
> fix: nominal wants issue #2010

- harper-wasm/src/lib.rs
- packages/harper.js/src/Linter.ts
- packages/harper.js/src/LocalLinter.ts
- packages/harper.js/src/WorkerLinter/index.ts
- packages/obsidian-plugin/src/State.test.ts
- packages/obsidian-plugin/src/State.ts
Fixes #2049 
The underlying problem was that Harper's dictionary was append-only. When a partial entry was added while typing, it was never removed. I've added a new method `clearWords`, and set up the plugin to call it before pushing new words to the user dictionary.
Manually + unit tests.
> fix(obsidian): properly manage dictionary

- packages/chrome-plugin/src/options/Options.svelte
Fixes #2058
We use a Svelte rune to manage state on the frontend of the options page. When Firefox tried to perform a structured clone to send it to the service worker, it crashed. To fix this, I set it to take a static snapshot before sending it.
Manually.
> fix(chrome-plugin): errors saving rule state in Firefox

- packages/chrome-plugin/src/contentScript/index.ts
Fixes #2060
Harper shouldn't be running on the Discord search box, or any other combo box.
Manually.
> fix(chrome-ext): disable on comboboxes

- packages/chrome-plugin/src/contentScript/index.ts
- packages/chrome-plugin/src/isWordPress.ts
For a while now, Harper has performed quite well on WordPress pages. I test this quite a bit in my role at [Automattic](https://automattic.com/). As that is the case, I figured we would just enable Harper automatically for all pages that appear to be WordPress.
Manually.
> feat(chrome-ext): enable by default on WordPress pages
