Automattic/harper

harper-core/src/linting/spelled_numbers.rs
harper-core/src/spell/hunspell/attributes.rs
harper-core/src/spell/mod.rs
harper-ls/src/backend.rs

This PR treats email as a plain text format

feat: Add Email Support

---

README.md

Several issues (#133, #166, #113) I have read refer to the fact that Harper only supports American English, this will add a small blurb about language support and encourage contribution.

fix: add blurb on language support and change count of ways to use

---

.github/workflows/build_harper_ls.yml

Windows GitHub Actions builds missing dependency

---

Cargo.lock
harper-comments/Cargo.toml
harper-comments/src/comment_parser.rs

Had to use a weird old version of tree-sitter-haskell for dependencies to work out.

feat(#331): Haskell Comment Support

---

packages/web/src/routes/docs/integrations/language-server/+page.md
packages/web/src/routes/docs/integrations/neovim/+page.md

@EphemeralDev, I've added instructions for installing Harper through Scoop. Since I'm not familiar with how Scoop works, can you confirm that this looks right?

docs: added Scoop instructions

---

packages/web/src/routes/docs/integrations/language-server/+page.md
packages/web/src/routes/docs/integrations/neovim/+page.md

I just discovered that someone has create a Homebrew formulae for Harper. What joy! I've added it to the installation documentation on the website. 
@lukasmwerner does this all look right? Is there anything that should be added?

docs: added Homebrew as an installation method

---

harper-core/src/linting/matcher.rs

feat(#422): add `same than` -> `same as` matcher trigger

---

harper-core/README.md

I moved the comma from before "however" to after it and broke it into two sentences. The comma is now where we would pause slightly in speech.

missing definite article, comma placement

---

harper-core/src/linting/proper_noun_capitalization_linters.rs

from plural to possessive = of Saint Valentine

correct Valentine's Day

---

packages/web/src/routes/docs/integrations/zed/+page.md

lighting-fast → lightning-fast

typo in zed integration doc

---

harper-comments/tests/language_support_sources/issue_96.lua
harper-comments/tests/language_support_sources/issue_96.rb

we have situation ... → we have **a** situation ...

missing indefinite article in comments

---

packages/web/src/routes/docs/contributors/dictionary/+page.md

I truly despise git but I finally got it to let me submit a fix in the docs for the problem addressed in issue 416 on agreement with complement or object instead of subject: https://github.com/Automattic/harper/issues/416

fix agreement error in docs

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/report-grammatical-error.md

The number of issues we've been getting is great. This commit helps newcomers structure them in a way that reduces the amount of back-and-forth needed to get them resolved.

feat: issue templates

---

packages/web/src/routes/docs/integrations/language-server/+page.md
packages/web/src/routes/docs/integrations/neovim/+page.md

In #536, it was revealed that you may need an additional dependency on certain platforms. This PR updates the documentation to mention it.

docs: mention #536 on installation pages

---

packages/vscode-plugin/README.md
packages/web/src/routes/docs/integrations/visual-studio-code/+page.md

Just some minor improvements to the instructional material for the Visual Studio Code plugin.
I'm open to feedback or revisions.

docs(vscode): revised introductional material

---

harper-core/dictionary.dict

Also added some dictionary entries.
Also sorted some entries into the right spot given that the older hunspell part of the dictionary sorted first by case and then by alphabetical order.

chore: correct some affix annotations

---

harper-core/dictionary.dict

found by using my `just sampleforms` feature from PR https://github.com/Automattic/harper/pull/646

chore: fixes to curated dictionary affixes

---

harper-core/src/linting/lint_group.rs
harper-core/src/linting/mod.rs
harper-core/src/linting/proper_noun_capitalization_linters.rs

Bonus: added Central America to North and South America

feat: multi-word proper nouns for Canada

---

harper-core/dictionary.dict
harper-core/src/linting/lint_group.rs
harper-core/src/spell/dictionary.rs
harper-core/src/spell/fst_dictionary.rs
harper-core/src/spell/merged_dictionary.rs
harper-core/src/spell/mutable_dictionary.rs
harper-wasm/src/lib.rs
packages/harper.js/package.json
packages/harper.js/src/Linter.test.ts
packages/harper.js/src/Linter.ts
packages/harper.js/src/LocalLinter.ts
packages/harper.js/src/WorkerLinter/index.ts
packages/obsidian-plugin/src/index.ts
packages/obsidian-plugin/src/lint.ts

Works towards #603. Also implements a primitive version of #547. I've elected to disallow reading and writing of the curated dictionary, since it feels unnecessary to my immediate use-case.

feat(harper.js): allow modification to the dictionary.

---

harper-core/src/linting/phrase_corrections.rs

Fixes #680 by making the rule more specific.

fix(core): make `ChangeTack` lint more specific

---

harper-core/src/linting/back_in_the_day.rs

Also the unit tests from my version of this lint I was working on yesterday.
Let me know if this is the wrong kind of pull request.
Let me know if my tests should be renamed to match yours.

feat: another exception for "back in the days before"

---

harper-core/dictionary.dict

This PR adds a couple of technical terms to the dictionary. And also my surname... I checked the dictionary and there are some other surnames in there too, so I hope that's okay.

feat(core): added technical words to dictionary

---

harper-core/src/linting/then_than.rs

fix(core): address edge cases in `ThenThan` rule

---

harper-core/src/linting/phrase_corrections.rs

Resolves #732 with a new rule.

feat(core): add rule that corrects `ban together`

---

harper-core/src/linting/proper_noun_capitalization_linters.rs
harper-core/src/title_case.rs

#798
I've added some tests to make double-sure that #798 does not exist on `master` anymore.
I've also manually opened Obsidian to confirm.

test(core): issue #798

---

harper-core/dictionary.dict

N/A
Improve dictionary while running Harper over YouTube video transcripts.

chore: add words, fix annotations

---

harper-core/dictionary.dict

N/A
Add new words and fix annotations based on transcriptions of YouTube videos I watched.

chore: curate dictionary

---

harper-core/src/linting/phrase_corrections.rs

N/A
Sometimes the word "monumentous" is a jokey play on words, but sometimes its used unwittingly by a writer who doesn't know they probably meant to use "momentous" or "monumental".
- I added an atomic test with just this word.
- I also added a real-world sentence using this word that I found on the Internet.
- [Quora](https://www.quora.com/Is-monumentous-a-word-Ive-been-using-it-a-long-time-but-now-Ive-discovered-there-seems-to-be-some-debate-as-to-its-validity)
- [r/footballcliches](https://www.reddit.com/r/footballcliches/comments/1fv4lgy/monumentous_is_not_a_word/)
- [Change.org](https://www.change.org/p/mikyla-bowen-make-the-word-monumentous-a-real-word)
- [Fritinancy](https://nancyfriedman.typepad.com/away_with_words/2008/01/word-of-the-wee.html)

feat: flag "monumentous" and offer "momentous" and "monumental"

---

harper-core/dictionary.dict

Includes a fix for #858 ("theming")
Added words to dictionoary, adjusted affix annotations.
I also added a term with a space and a term with a hyphen to see how well they are supported.
N/A

Dictionary curation 2025 03 08

---

harper-core/src/linting/phrase_corrections.rs
harper-core/src/parsers/plain_english.rs

Fixes #525 
Fixes "worse" and "worst" used in each other's place in half a dozen common contexts.
- I implemented one atomic test and one real-world test taken from GitHub for each variant.
- `cargo tests` then passes with no fails.

feat: implement #525 (worse/worst confusion)

---

harper-core/dictionary.dict

N/A
Add words and adjust affix annotations while dogfooding YouTube transcripts.
N/A
Using `just getforms` with new words + affixes before saving to make sure bogus forms don't slip past.

Dictionary curation 2025 03 11

---

packages/web/src/routes/docs/integrations/language-server/+page.md

N/A
- Fix default location of user dictionary.
- Fix description of userDictPath.
Run `just dev-web` and view in browser.

docs: fix user dictionary

---

packages/web/src/routes/docs/contributors/visual-studio-code/+page.md

N/A
- 2 grammar mistakes of the type described in issue #384
- 1 grammar mistake of the type described in #436
N/A

docs: fix 3 grammar mistakes

---

packages/web/src/app.css

No issue. Just improvement.
https://github.com/user-attachments/assets/43d21655-c6bd-4af0-a62c-c6b2ed0798b1

feat(web): add mask-image to header

---

harper-core/src/linting/phrase_corrections.rs

Fixes #965
This was a bad phrase that never should have been added. This PR just removes it.
It's a simple enough change. No additional testing required.

fix(core): remove bad phrase

---

harper-core/src/linting/adjective_of_a.rs

N/A
I found another false positive with the "How big of a deal" linter.
No longer flags "much of a".
I also cleaned up the code.
- I added a new test using a sentence found on GitHub.
- `cargo tests` passes 100%

fix: handle another false positive in "adjective of a"

---

.github/ISSUE_TEMPLATE/suggest-a-feature.md

N/A
I thought it might be nice to have a github issue template for feature requests. I tried to make it easy to see that it's not for requesting new grammar errors.
Please edit in anyway, or decide not to publish for any reason.
N/A

template for feature requests on github

---

packages/vscode-plugin/src/tests/suite/integration.test.ts

Fixes #1001.
See https://github.com/Automattic/harper/issues/1001#issuecomment-2770966688
N/A
`just precommit`, and with GitHub Actions to soon follow.

fix(vscode-plugin): sleep a longer time after openUntitled

---

packages/web/src/routes/docs/about/+page.md

n/a
Small grammar mistake, fixed.
n/a
n/a

docs: fix grammar

---

Dockerfile
packages/harper.js/docs.sh
packages/web/demo_wp_blueprint.json
packages/web/src/routes/docs/contributors/author-a-rule/+page.md

This PR updates the "Author a Rule" page in our documentation to reflect recent changes to how rules are registered and written. It also adds some additional (minor) information regarding when to open a PR.

docs(core): update the `Author a Rule` page to align with code

---

harper-wasm/src/lib.rs
packages/harper.js/src/Linter.test.ts
packages/harper.js/src/Linter.ts
packages/harper.js/src/LocalLinter.ts
packages/harper.js/src/WorkerLinter/index.ts
packages/obsidian-plugin/src/index.ts
packages/web/src/lib/Editor.svelte
packages/wordpress-plugin/src/harper/RichText.ts

#1005
Significantly improved the performance of clients using `harper.js`, particularly for large documents. Works by reducing the overhead caused by serialization/deserialization.
Updated existing unit tests. They pass.

feat(harper.js): significantly improve worker performance

---

harper-core/src/linting/adjective_of_a.rs

N/A
I'd been vacillating about "more of a" but I've decided to stop flagging it as it often looks right.
I've added logic to rule out -ing forms since those are verbs that act as both nouns and adjectives and "of a" before a noun is legit.
I added a new unit test based on the -ing form that led me to implement this.
`cargo test` passes

fix: new logic and false positives

---

harper-core/src/linting/adjective_of_a.rs

N/A
The word "side" is an adjective but "side of a" is not like "big of a" since it's usually a noun.
Added a new unit test based on the sentence that brought it to my attention.
Ran `cargo test`

chore: "side of a" false positive

---

harper-core/dictionary.dict

N/A
New words added, affix annotations tweak, a few comments.

Dictionary curation 2025 04 04

---

harper-core/dictionary.dict

N/A
New words and affix annotation fixes found while dogfooding on YouTube transcripts.

Dictionary curation 2025 04 17

---

packages/web/src/routes/docs/contributors/obsidian/+page.md
packages/web/vite.config.ts

I was asked for some technical details about the Obsidian plugin in Discord. This PR aims to answer these questions by way of a contributor's guide in the documentation.

docs(obsidian): wrote initial contributor's guide

---

packages/obsidian-plugin/src/index.ts

Fixes #1113
Super simple stuff. Read the code.

fix(obsidian): console contamination

---

harper-core/dictionary.dict

Adds https://en.wikipedia.org/wiki/Schengen,_Luxembourg (also for https://en.wikipedia.org/wiki/Schengen_Area)

dictionary: Added Schengen

---

harper-core/src/linting/phrase_corrections.rs

N/A
Another common one these days: writing "as well" as a single word.
I added three unit tests using sentences from GitHub.

feat: aswell→as well

---

harper-core/src/linting/lets_confusion/no_contraction_with_verb.rs

Fixes #1157
It turned out not to be due to being followed by an adverb.
Rather it's a symptom of `us` getting tagged as a noun as well as a pronoun due to something in the harper dictionary/affix system conflating `us` and `US`, which is a noun.
I added a special case to the part that checks if the word after "let" is a noun.
I added a new unit test which failed the previous version.

Fix false positive in let/lets→let's

---

.github/workflows/build_harper_binaries.yml
.github/workflows/precommit.yml
.github/workflows/release_harper_binaries.yml
justfile
package.json

Addresses problems highlighted in #1160 
This PR intends to improve the speed of our GitHub Actions `precommit` job, mainly by caching various stages.
Before this PR, the `precommit` workflow took ~30 minutes. After this PR, it takes only 6 minutes.

build: add caching

---

harper-core/src/linting/hop_hope/mod.rs
harper-core/src/linting/suggestion.rs

Fixes #1068 in a more concrete way. 
I've added some unit tests.

fix(core): ignore whitespace when matching case

---

harper-core/dictionary.dict

n/a
Adds the words "unpublish" (added `U` flag to `publish`) and "unpublishing" (added `U` flag to `publishing`). 
n/a

chore(harper-core/dictionary): add unpublish(ing) forms with flags

---

harper-core/src/linting/phrase_corrections.rs

N/A
I just heard somebody say "once a while" instead of "once in a while" on YouTube. So I did a search and it's very common, even on GitHub.
I added a unit test using a sentence from GitHub.

feat: once a while→once in a while

---

harper-core/dictionary.dict

n/a
Adds a few developer-related nouns: NixOS, a popular operating system; WSL, Microsoft's Windows Subsystem for Linux; OCaml, a programming language; Vercel and Netlfiy are two popular hosting providers for web developers; SolidJS and Vue are popular web developer projects/frameworks/tools.
n/a
n/a

chore(harper-core/dictionary): add developer-related nouns

---

harper-core/src/linting/inflected_verb_after_to.rs

Fixes #1185
Added heuristics for -ed form of a verb after "to"
Refactored to allow for adding similar heuristics for other verb forms.
Added heuristics to keep the old tests passing with the new heuristics in place.
I added the phrase from the issue as a new unit test.

fix: heuristics to fix "comparison to expected results"

---

harper-cli/src/main.rs

Makes `harper-cli` fallback to the `PlainEnglish` parser when encountering an unimplemented file extension. When this happens, a message will be printed to notify the user of this occurring.
This change allows `harper-cli` to be used on a wider selection of files, like `.txt` files and those without an extension.
A potential concern is that, by printing the fallback warning message, we are changing the output of some `harper-cli` commands. If something relies on `harper-cli`'s output being in a particular format, it could break.
- `cargo test`
- Compiled and manually tested. I tested `harper-cli` with `.cs`, `.md`, and `.txt` files, and also those without an extension. The expected behavior was observed and no issues were noticed.

feat(cli): fallback to `PlainEnglish` parser

---

harper-core/dictionary.dict
harper-core/src/linting/adjective_of_a.rs
harper-core/tests/text/linters/Alice's Adventures in Wonderland.snap.yml
harper-core/tests/text/linters/The Great Gatsby.snap.yml

N/A
New words, annotation corrections and tweaks.
Moved a new word to the correct section at the bottom.
Added "bastard" to the list of exceptions in the adjective-of-a linter since it's more usually a noun than an adjective.

Dictionary curation 2025 05 13

---

packages/chrome-plugin/src/Highlights.ts
packages/chrome-plugin/src/PopupHandler.ts
packages/chrome-plugin/src/ProtocolClient.ts
packages/chrome-plugin/src/background/index.ts
packages/chrome-plugin/src/contentScript/index.ts

This PR updates the Chrome extension to support even more sites. It also introduces an LRU cache that speeds up linting performance at the cost of slowing down config updates.
Manually.

feat(chrome-ext): add support for more sites

---

harper-core/src/ignored_lints/lint_context.rs
harper-core/src/ignored_lints/mod.rs
harper-core/src/lib.rs
harper-wasm/src/lib.rs
packages/chrome-plugin/src/Highlights.ts
packages/chrome-plugin/src/ProtocolClient.ts
packages/chrome-plugin/src/SuggestionBox.ts
packages/chrome-plugin/src/TextFieldRange.ts
packages/chrome-plugin/src/background/index.ts
packages/chrome-plugin/src/computeLintBoxes.ts
packages/chrome-plugin/src/protocol.ts
packages/chrome-plugin/src/unpackLint.ts
packages/harper.js/src/Linter.test.ts
packages/harper.js/src/Linter.ts
packages/harper.js/src/LocalLinter.ts
packages/harper.js/src/WorkerLinter/index.ts
packages/harper.js/src/binary.ts

This PR adds the ability to ignore lints to the Harper Obsidian plugin. It also refactors some of the rendering logic for the suggestion popup.
Manually.

feat(chrome-ext): ignore lints

---

harper-core/dictionary.dict
harper-core/src/linting/adjective_of_a.rs
harper-core/tests/text/linters/Alice's Adventures in Wonderland.snap.yml
harper-core/tests/text/linters/Computer science.snap.yml
harper-core/tests/text/linters/Difficult sentences.snap.yml
harper-core/tests/text/linters/Part-of-speech tagging.snap.yml
harper-core/tests/text/linters/The Constitution of the United States.snap.yml
harper-core/tests/text/linters/The Great Gatsby.snap.yml

#1269
Added new words
Corrected some affix annotation
Added two more exceptions to the adjective-of-a linter for words which are technically adjectives too but much more commonly nouns so don't get used in the way the linter corrects.
I added a unit test for the adjective-of-a exception.

chore: new words, annotation corrections, adj-of-a exceptions

---

Cargo.lock
harper-comments/Cargo.toml
harper-comments/src/comment_parser.rs
harper-comments/tests/language_support.rs
harper-comments/tests/language_support_sources/basic_kotlin.kt
harper-core/dictionary.dict
packages/vscode-plugin/package.json
packages/web/src/routes/docs/integrations/language-server/+page.md

Per #79
I did not add Kotlin to the VS Code extension, since it does not appear that VS Code supports the language out of the box. I'd love to be proved wrong, @mcecode.
It's been added to `harper-ls`, though, which should pave the way for Neovim, Helix, Emacs, etc.
Unit and integration tests.

feat(comments): add Kotlin support

---

harper-core/src/linting/phrase_corrections.rs

N/A
Corrects the colloquial "take it personal" to the standard "take it personally".
I added a unit test with the first sentence I found using it on GitHub.

feat: take it personal→take it personally

---

packages/web/package.json
packages/web/src/app.html
packages/web/src/routes/+layout.svelte
packages/web/src/routes/+page.svelte
pnpm-lock.yaml

Nothing crazy, just some tweaks for SEO purposes.

feat(web): tweaks for SEO

---

harper-core/src/linting/lint_group.rs

Tiny PR: Just commenting and refactoring the `LintGroup` code for readability.

refactor(core): box within function

---

.github/workflows/build_web.yml
packages/chrome-plugin/src/background/index.ts
packages/web/src/routes/uninstall-browser-extension/+page.svelte

When a user uninstalls the Harper Chrome extension, we would love to know why. To that effect, I've added a form to the website, and instructed the chrome extension to redirect there upon uninstallation.
For the sake of speed, I've used Google Forms for this.
Manually.

feat(web): add page with feedback form

---

packages/web/src/routes/docs/contributors/architecture/+page.md
packages/web/src/routes/docs/faq/+page.md
packages/web/src/routes/docs/integrations/sublime-text/+page.md
packages/web/vite.config.ts

Added documentation for integration with Sublime Text
Followed these instructions to setup my Sublime Text LSP to work with Harper.

docs(sublime-text): added sublime text integration

---

harper-core/src/linting/phrase_corrections.rs

N/A
It turns out people mix up "peace" and "piece" pretty often in this idiom. So here's a lint for it.
I added a unit test using a sentence found on GitHub.

feat: piece of mind→peace of mind

---

packages/obsidian-plugin/src/lint.ts

I wasn't a huge fan of the style of the code blocks introduced by #1240, so this PR tweaks them.
Before:
After:
Manually.

feat(obsidian): tweak style of code block

---

harper-core/dictionary.dict
harper-core/tests/text/linters/Alice's Adventures in Wonderland.snap.yml
harper-core/tests/text/linters/Computer science.snap.yml
harper-core/tests/text/linters/Part-of-speech tagging.snap.yml
harper-core/tests/text/linters/The Constitution of the United States.snap.yml
harper-core/tests/text/linters/The Great Gatsby.snap.yml

Adds `IMSI`, `GSM`, `CDMA`, `LTE`, `HDR`, `IPS`, `Exynos`.
Due to sorting, this also changes the position of a handful of other words in the same word group.

dictionary: add some (mostly) phone-related terms

---

harper-core/src/linting/phrase_corrections/mod.rs
harper-core/src/linting/phrase_corrections/tests.rs

N/A
Sort the phrase corrections. This makes it easier to see what's already in there
and find one you're looking for at a glance.
Note that at least one duplicate becomes apparent: baited breath/bated breath
`cargo test` still passes clean.

chore: sort alphabetically

---

harper-core/src/linting/phrase_corrections/mod.rs
harper-core/src/linting/phrase_corrections/tests.rs

Closes #346
These are just some simple common phrase corrections.

feat(core): add linter for #346

---

harper-core/src/linting/its_contraction.rs
harper-core/src/linting/phrase_corrections/mod.rs

Partially covers #381
Manually + existing tests + new tests

feat(core): cover case from #381 + remove useless rule

---

harper-core/src/linting/phrase_corrections/mod.rs
harper-core/src/linting/phrase_corrections/tests.rs

N/A
I saw somebody spell "on top" as a single word for the first time, did a search, and it's everywhere.
I picked one sentence using it on GitHub and used it as a unit test.

feat: ontop of→on top of

---

harper-core/src/linting/phrase_set_corrections/mod.rs
harper-core/src/linting/phrase_set_corrections/tests.rs

N/A
Was just watching a YouTube video on the roadmap for Zig where the speaker said "chomping at the bit".
This is not new as the verb "champ" is very specialized to the equestrian origin of the idiom.
I included a concise explanation of the origin in the Description but left it out of the Message.
I added a unit test for each inflection from sentences mostly source from GitHub.

feat: chomp at the bit→champ at the bit

---

packages/web/src/routes/install-browser-extension/+page.svelte
packages/web/src/routes/request-browser-support/+page.svelte

Adds more information to the onboarding page, hopefully clearing up a point of common confusion.
We will have to see from responses from real users.

feat(web): add detail to onboarding page + add site request form

---

harper-core/src/linting/phrase_set_corrections/mod.rs
harper-core/src/linting/phrase_set_corrections/tests.rs

N/A
Just heard this in a YouTube video by a European non-native English speaker.
A quick Google search made it seemed very common (-;
I added a unit test for each inflection using a sentence from GitHub.

feat:make it seems→make it seem

---

harper-core/dictionary.dict
harper-core/src/linting/closed_compounds.rs
harper-core/src/linting/compound_nouns/compound_noun_after_det_adj.rs
harper-core/src/linting/compound_nouns/mod.rs
harper-core/src/linting/how_to.rs
harper-core/src/linting/possessive_your.rs
harper-core/src/linting/pronoun_contraction/should_contract.rs
harper-core/src/linting/pronoun_knew.rs
harper-core/tests/text/linters/Alice's Adventures in Wonderland.snap.yml
harper-core/tests/text/linters/The Great Gatsby.snap.yml
harper-core/tests/text/tagged/Alice's Adventures in Wonderland.md
harper-core/tests/text/tagged/Computer science.md
harper-core/tests/text/tagged/The Great Gatsby.md

- #1553
- #1518 
- #1496
- #1492 
- #1508 
- #1298
Fixes a wide variety of false-positives found principally in GitHub issues.
Additional unit tests derived from the issues themselves.

Fix variety of false-positives

---

harper-core/dictionary.dict
harper-core/tests/text/linters/Alice's Adventures in Wonderland.snap.yml
harper-core/tests/text/linters/The Great Gatsby.snap.yml

N/A
Mostly new words from trending GitHub repo `README`s.

Dictionary curation 2025 07 23

---

harper-core/src/linting/noun_countability.rs

N/A
This linter had false positives when the mass noun was part of a hyphenated compound noun: 
I used the sentence where I spotted this to create a new unit test.

feat: don't flag mass noun in hyphenated compound

---

harper-core/src/linting/its_contraction.rs
harper-core/src/linting/its_possessive.rs
harper-core/src/linting/lint_group.rs
harper-core/src/linting/nominal_wants.rs
harper-core/tests/text/linters/Alice's Adventures in Wonderland.snap.yml
harper-core/tests/text/linters/Computer science.snap.yml
harper-core/tests/text/linters/Part-of-speech tagging.snap.yml
harper-core/tests/text/linters/The Great Gatsby.snap.yml

A follow-on from #1614 
This PR fixes a number of small (but annoying) false-positives in the core engine.
Additional unit tests + fuzzing

fix(core): several false-positives

---

harper-core/src/expr/sequence_expr.rs
harper-core/src/linting/its_possessive.rs
harper-core/src/linting/missing_preposition.rs
harper-core/src/linting/pronoun_inflection_be.rs
harper-core/tests/text/linters/Difficult sentences.snap.yml

#1658 + #1585
Added exceptions to rules to reduce their false-positives.
Additional unit tests

fix(core): false-positives

---

packages/harper.js/examples/raw-web/index.html

Discussed in Discord.
Updates the CDN example of `harper.js` to `v0.54.0` to show proper use of the binary API.
Manually.

feat(docs): update the CDN example to `v0.54.0`

---

harper-core/src/linting/pronoun_inflection_be.rs
harper-core/tests/text/linters/this and that.snap.yml

#1682
Fixes a false-positive in #1682 by using the new NP chunker.
Additional unit test.

fix(core): false-positive from #1682

---

harper-core/src/linting/how_to.rs

#1492
Adds an exception to the `HowTo` rule for the word `does`.
Additional unit tests.

fix(core): address second part of #1492

---

harper-core/src/linting/pronoun_contraction/should_contract.rs
harper-core/tests/text/linters/The Great Gatsby.snap.yml

#1701 #1673 
Adds a simple exception to the `ShouldContract` rule to avoid the false-positive from the linked issues.
Additional tests + fuzzing.

fix(core): edge-case in `ShouldContract` rule

---

harper-core/dictionary.dict
harper-core/tests/run_tests.rs
harper-core/tests/text/linters/Computer science.snap.yml
harper-core/tests/text/linters/The Great Gatsby.snap.yml

Fixes #1717
Mostly new words, including "uneditable" as requested in #1717

chore: new words

---

harper-core/src/linting/phrase_corrections/mod.rs
harper-core/src/linting/phrase_corrections/tests.rs

N/A
Just a few days after finding and fixing "go through great lengths" I've stumbled across another variant of "go to great lengths".
I added a unit test using the sentence from the ratatui-image docs that brought this mistake to my attention.

feat:to a great length→to great lengths

---

harper-typst/src/lib.rs
harper-typst/src/typst_translator.rs

Closes #1898
There were more `unwrap`s that I missed inside of macros.
Waiting on test case from issue author.

fix(#1898): do not panic on other typst parsing error

---

packages/web/src/lib/Editor.svelte
packages/web/src/lib/LintCard.svelte
packages/web/src/routes/+page.svelte

Addresses feedback from #1878 
In #1878, some additional features were requested from the website's editor. Namely:
1. Ignoring lints
2. Jumping to a selected lint
3. Expanding / collapsing all lints in the sidebar
I've also added a button to ignore all lints.
Manually.

feat(web): apply feedback from #1878

---

harper-comments/src/comment_parser.rs

Following this issue https://github.com/Automattic/harper/issues/79.
This PR adds `cljd`, the extension for files using the [ClojureDart](https://github.com/Tensegritics/ClojureDart) dialect.
I've also reordered the extension list so it reads more alphabetically.
It builds on top of #1520.
Not relevant.
I did not test it since it is adding a known extension and not touching any logic.

feat: support ClojureDart

---

harper-core/src/parsers/org_mode.rs

Fixes tab-related linting issues in org-mode list structures.
The issue was the french spaces, where it translates to different spaces, and org-list failed with the same issue.
- [x ] I have performed a self-review of my own code
- [x ] I have added tests to cover my changes

fix: org-mode add list item parsing with tab normalization

---

packages/chrome-plugin/src/background/index.ts
packages/chrome-plugin/tests/hn.spec.ts
packages/chrome-plugin/tests/testUtils.ts
packages/lint-framework/src/lint/Highlights.ts

The highlights were not rendered in the correct place on the page.
I've removed the bit of `computeLintBoxes` that accounts for a possible closest positioned ancestor. It wasn't working properly and removing it seems to have no downside.
Additional tests.

fix(web): will now work on Hacker News
